<!-- User Profile -->
<div class="box box-primary">
    <div class="box-body box-profile">
        <img class="profile-user-img img-responsive img-circle"
            src="/img/avatar5.png">
        <h3 class="profile-username text-center">
            <?php echo $user->getName(); ?>
        </h3>
        <p class="text-muted text-center">
            <?php echo $user->getEmail(); ?>
        </p>
        <ul class="list-group list-group-unbordered">
            <li class="list-group-item">
                <b>Orders</b>
                <span class="pull-right-container">
                    <a class="label pull-right bg-blue">
                        <?php echo count($orders); ?>
                    </a>
                    <?php if($countOfOrderByStatus[1] > 0) { ?>
                        <small class="label pull-right bg-red margin-r-5">
                            <?php echo $countOfOrderByStatus[1]." new";?>
                        </small>
                    <?php } ?>
                    <?php if($countOfOrderByStatus[2] > 0) { ?>
                        <small class="label pull-right bg-blue margin-r-5">
                            <?php echo $countOfOrderByStatus[2]." ship";?>
                        </small>
                    <?php } ?>
                    <?php if($countOfOrderByStatus[3] > 0) { ?>
                        <small class="label pull-right bg-yellow margin-r-5">
                            <?php echo $countOfOrderByStatus[3]." success";?>
                        </small>
                    <?php } ?>  
                </span>
            </li>
            <li class="list-group-item">
                <b>Total Pays:</b>
                <small class="label bg-blue pull-right"><?php echo $total_pays; ?>$</small>
            </li>
            <li class="list-group-item">
                <b>Purchased Items:</b>
                <small class="label bg-blue pull-right"><?php echo $total_purchased; ?></small>
            </li>
        </ul>
    </div>
</div>

<!-- User' Information -->
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Information</h3>
    </div>
    <div class="box-body">
        <strong>
            <i class="fa fa-map-marker margin-r-5"></i>
            Address
        </strong>
        <p class="text-muted">
            <?php echo $user->getFullAddress(); ?>
        </p>
        <hr>
        <strong>
            <i class="fa fa-phone margin-r-5"></i>
            Phone
        </strong>
        <p class="text-muted">
            <?php echo $user->getPhone(); ?>
        </p>
        <hr>
    </div>
</div>