<div class="nav-tabs-custom">
	<ul class="nav nav-tabs">
		<li class="active">
			<a href="#latest-order" data-toggle="tab">Latest Orders</a>
		</li>
		<li>
			<a href="#action" data-toggle="tab">Action</a>
		</li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane active" id="latest-order">
			<?php include_once '_order-table.phtml';?>
		</div>

		<div class="tab-pane active" id="action">
			
		</div>
	</div>
</div>