<div class="box-body">   
    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>STT</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Option</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($users as $user): ?>
                <tr>
                    <td><?php echo ++$i ?></td>
                    <td><?php echo $user->getName() ?></td>
                    <td><?php echo $user->getEmail() ?></td>
                    <td><?php echo $user->getPhone() ?></td>
                    <td><?php echo $user->getAddress() ?></td>
                    <td><a class="btn btn-warning" href="#">Show</a>
                        <form method="POST" action="#" accept-charset="UTF-8" 
                            id="form-delete" class="inline">
                            <input class="btn btn-danger" type="submit" value="Delete">
                        </form>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
