<div class="success-outer">
    <div class="success-inner">
        <div class="icon-stack text-center">
            <i class="fa fa-check success"></i>
            <h1>You're all Set !</h1>
            <span>Order #: 17392 </span>
            <p class="lead text-center">
                Well, Isn't that fantastic? <br/>
                We hope you enjoy your purchase!
            </p>
            <p class="text-center">
            </p>
<!--            <ul class="tag_ul">-->
<!--                <li>B&O Beo Labs III Speaker</li>-->
<!--                <li>Ottoman Chaise </li>-->
<!--                <li>Me and Earl and the Dying Girl Ebook</li>-->
<!--                <li class="last">YAMAHA MONTAGE 8 Synthesizer 88 Key</li>-->
<!--            </ul>-->
        </div>

    </div>
</div>