<div class="shopping-cart">
    <div class="shopping-cart-content">
        <!-- Title -->
        <h2>Your cart</h2>
        <div class="divider"></div>

        <div class="item" id="item1">
            <div class="buttons">
                <span class="delete-btn"></span>
                <span class="like-btn"></span>
            </div>

            <div class="image">
                <img src="/img/img1.jpg" alt=""/>
            </div>

            <div class="description">
                <span>Our Legacy</span>
                <span>Brushed Scarf</span>
                <span>Brown</span>
            </div>

            <div class="quantity">
                <button class="minus-btn" type="button" name="button">
                    <img src="/img/minus.svg" alt=""/>
                </button>
                <input type="text" name="name" value="1">
                <button class="plus-btn" type="button" name="button">
                    <img src="/img/plus.svg" alt=""/>
                </button>
            </div>

            <div class="total-price">$349</div>
        </div>

        <div class="item" id="2">
            <div class="buttons">
                <span class="delete-btn"></span>
                <span class="like-btn"></span>
            </div>

            <div class="image">
                <img src="/img/img1.jpg" alt=""/>
            </div>

            <div class="description">
                <span>Our Legacy</span>
                <span>Brushed Scarf</span>
                <span>Brown</span>
            </div>

            <div class="quantity">
                <button class="minus-btn" type="button" name="button">
                    <img src="/img/minus.svg" alt=""/>
                </button>
                <input type="text" name="name" value="1">
                <button class="plus-btn" type="button" name="button">
                    <img src="/img/plus.svg" alt=""/>
                </button>
            </div>

            <div class="total-price">$349</div>
        </div>
    </div>
</div>
