<div class="body-margin">
    <div class="row">
        <div class="grid-list-product col-md-12 col-md-offset-1">
            <div class="">
                <h1><?php echo $category->getName() ?></h1>
                <br>
                <hr>
            </div>
            <div class="list-product">
                <div class="row">
                    <?php foreach ($products as $product) { ?>
                        <div class="col-md-4 text-center animate-box">
                            <div class="product">
                                <div class="product-grid"
                                     style="background-image:url(<?php echo $product->getImage() ?>);">
                                    <?php if ($product->getSale() > 0) { ?>
                                        <span class="sale">Sale</span>
                                    <?php }; ?>
                                    <div class="inner">
                                        <p>
                                            <a class="icon addToCart"
                                               data-cart-add="<?php echo $product->getId(); ?>"
                                               data-cart-quantity="1"
                                               data-cart-name="<?php echo $product->getName(); ?>"
                                               data-cart-img="<?php echo $this->basePath($product->getImage()) ?>"
                                               data-cart-price="<?php echo $product->getSalePrice(); ?>">
                                                <i class="icon-shopping-cart"></i>
                                            </a>
                                            <a href="/product/view/<?php echo $product->getId() ?>" class="icon"><i
                                                        class="icon-eye"></i></a>
                                        </p>
                                    </div>
                                </div>
                                <div class="desc">
                                    <h3><a href="/product/view/<?php echo $product->getId() ?>">
                                            <?php echo $product->getName() ?>
                                        </a>
                                    </h3>
                                    <span class="price"><?php echo $product->getSalePrice() ?> USD</span>
                                </div>
                            </div>
                        </div>

                    <?php } ?>
                </div>
                <div class="paginator">
                    <?= $this->paginationControl($products,
                        'Sliding',
                        'application/partial/paginator',
                        ['route' => 'category',
                            'action' => 'view',
                            'id' => $category->getId()
                        ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
