
<div class="container category_list" id="content">
    <div class="clearfix">
        <!--        <div class="search-bar pull-left">-->
        <!--            <span class="lead">--><?php //echo $category->getName(); ?><!--</span>-->
        <!--        </div>-->
        <div class="dropdown pull-right">
            <span class="sort_by">Sort by: </span>
            <select class="btn btn-default">
                <option>Relevance</option>
                <option>Price High to Low</option>
                <option>Price Low to High</option>
                <option>Popular</option>
                <option>Best Selling</option>
                <option>Newest Items</option>
            </select>
        </div>
    </div>

    <div class="row clearfix mt15">
        <?php include_once 'view/_sidebar.phtml' ?>
        <?php include_once 'view/_listProduct.phtml' ?>
    </div>
</div>