<div class="grid-list-product">
    <div class=""> 
        <h1><?php echo $category->getName() ?></h1> 
        <br>
        <hr>
    </div>
    <div class="list-product">
        <div class="row">
            <?php foreach ($products as $product) { ?>
            <div class="col-md-4 text-center animate-box">
                <div class="product">
                    <div class="product-grid" style="background-image:url(<?php echo $product->getImage() ?>);">
                        <div class="inner">
                            <p>
                                <a href="single.html" class="icon"><i class="icon-shopping-cart"></i></a>
                                <a href="single.html" class="icon"><i class="icon-eye"></i></a>
                            </p>
                        </div>
                    </div>
                    <div class="desc">
                        <h3><a href="single.html"></a><?php echo $product->getName() ?></a></h3>
                        <span class="price">$<?php echo $product->getPrice() ?></span>
                    </div>
                </div>
            </div>
            
            <?php } ?>
        </div>
        <div class="paginator">
        <?= $this->paginationControl($products,
            'Sliding',
            'application/partial/paginator', 
            ['route' => 'category',
                'action' => 'view',
                'id' => $category->getId()
            ]); ?>
        </div>
    </div>
</div>