<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
    ->prependStylesheet($this->basePath('css/style.css'))
    ->prependStylesheet($this->basePath('css/admin.css'))
    ->prependStylesheet($this->basePath('assets/bootstrap/dist/css/bootstrap-theme.min.css'))
    ->prependStylesheet($this->basePath('assets/bootstrap/dist/css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
    ->prependFile($this->basePath('js/me.js'))
    ->prependFile($this->basePath('assets/bootstrap/dist/js/bootstrap.min.js'))
    ->prependFile($this->basePath('assets/jquery/dist/jquery.min.js'))
    
    ?>
</head>
<body>
    <?php include_once 'html/nav.php';?>
    
    <div class="row">
        <!-- uncomment code for absolute positioning tweek see top comment in css -->
        <!-- <div class="absolute-wrapper"> </div> -->
        <!-- Menu -->
        <?php include_once 'html/sidebar.php';?>

        <!-- Main Content -->
        <div class="container-fluid">
            <div class="side-body">
                <?= $this->content ?>   
            </div>
        </div>
    </div>

    <?= $this->inlineScript() ?>
</body>
</html>
