<?php
$this->headTitle('Sign in');

// $this->mainMenu()->setActiveItemId('login');

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Email address',
    'required' => true,
    'autofocus' => true
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Password',
    'required' => true,
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>

<div class="row">
    <div class="col-md-offset-4 col-md-3">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">Please sign in</h2>
            <?php if ($isLoginError): ?>
                <div class="alert alert-warning" role="alert">
                    Incorrect email and/or password.
                    <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
                </div>
            <?php endif; ?>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('email')); ?>
                <?php echo $this->formElement($form->get('email')); ?>
            </div>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('password')); ?>
                <?php echo $this->formElement($form->get('password')); ?>
            </div>
            <div class="checkbox">
                <label>
                    <?= $this->formElement($form->get('remember_me')); ?> keep me logged-in
                </label>
            </div>
            <?php echo $this->formElement($form->get('redirect_url')); ?>
            <?php echo $this->formElement($form->get('csrf')) ?>
            <a class="btn btn-cancel" href="<?= $this->url('register'); ?>">
                Register
            </a>
            <button class="btn btn-lg btn-primary" type="submit">Sign in</button>
        </form>
    </div>
</div>