<?php
$this->headTitle('Sign in');

// $this->mainMenu()->setActiveItemId('login');

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'required' => true,
    'autofocus' => true
]);

$form->get('password')->setAttributes([
    'class' => 'form-control',
    'required' => true,
]);
?>

<div class="row">
    <div class="col-md-4 col-md-offset-4 register">
        <div class="register-form">
            <h3>Sign in</h3>

            <?= $this->form()->openTag($form); ?>
            <?php if ($isLoginError): ?>
                <div class="alert alert-warning" role="alert">
                    Incorrect email and/or password.
                </div>
            <?php endif; ?>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('email')); ?>
                <?php echo $this->formElement($form->get('email')); ?>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-4">
                        <?php echo $this->formLabel($form->get('password')); ?>
                    </div>
                    <div class="col-md-8 text-right">
                        <span style="display: inline"><a href="/reset-password">Forgot your password?</a></span>
                    </div>
                </div>
                <?php echo $this->formElement($form->get('password')); ?>
            </div>
            <?php echo $this->formElement($form->get('redirect_url')); ?>
            <?php echo $this->formElement($form->get('csrf')) ?>
            <button class="btn btn-primary" type="submit">Sign in</button>
            <div class="checkbox">
                <label>
                    <?= $this->formElement($form->get('remember_me')); ?> Keep me signed in
                </label>
            </div>
            <?= $this->form()->closeTag(); ?>
            <div class="divider"></div>
            <button class="btn btn-cancel" onclick="location.href = '/register';">Create your account</button>
        </div>
    </div>
</div>