<div class="panel panel-default">
    <div class="panel-heading">
        <div class="add_heading clearfix">
            <a href="#" class="pull-right">Change</a>
            <p> Shipping address<span>Cupertino, CA</span></p>
        </div>
    </div>
    <div class="panel-body">
        <address>
            14, Wespres Hills, Saratoga County,NY 12866, <img src="http://premium-templates.org/ecommerce/html5/darwin/demo/img/usflag.png" width="16" height="16" /> USA
        </address>
    </div>
</div>