<div class="panel panel-default">
    <div class="panel-heading">
        <p><b>Review Product</b></p>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-2 col-sm-2 col-md-3 col-xs-12">
                <div class="review_img">
                    <img src="http://premium-templates.org/ecommerce/html5/darwin/demo/img/cupcut.jpg" class="img-responsive"/>
                </div>
            </div>
            <div class="col-lg-6 col-sm-6 col-md-4 col-xs-12">
                <div class="product_description">
													<span>
														Copper Eatset by Marco Polo Eatlery<br/>
														Box Set of: <b>24</b><br/>
														Price: <b>$65</b><br/>
														Quantity: <b>1</b>
													</span>
                </div>
            </div>
            <div class="col-lg-3 col-sm-3 col-md-4 col-xs-12">
                <div class="shipping_details">
													<span>
														Shipping-charge: <b>$34</b>
														Ships From: <br /> <img src="http://premium-templates.org/ecommerce/html5/darwin/demo/img/franceflag.png" width="16" height="16" /> <b>France</b> <br /> to <br /><img src="/ecommerce/html5/darwin/demo/img/international.png" width="16" height="16" /> <b>Worldwide</b><br/>
														Estimated Delivery:<br/><b>4</b> to <b>6</b> days

													</span>
                </div>
            </div>
        </div>
    </div>
</div>