<?php
$this->headTitle('Shipping information');

$form->get('full_name')->setAttributes([
    'class' => 'form-control',
]);

$form->get('address')->setAttributes([
    'class' => 'form-control',
]);

$form->get('phone')->setAttributes([
    'class' => 'form-control',
]);
if($user != null){
    $form->get('user_id')->setAttributes([
        'value' => $user->getId(),
    ]);
}

$form->get('submit')
    ->setAttributes(['class' => 'btn btn-primary btn-lg']);

$form->prepare();
?>

<div class="panel panel-default">
    <div class="panel-heading">
        <p >Choose a shipping address</p>
    </div>
    <div class="panel-body">
        <div class="user-details">
            <div class="form-group">
                <label>Full Name </label>
                <input type="text" class="form-control" />
            </div>
        </div>
        <div class="user-details">
            <div class="row">
                <div class="col-lg-6 col-sm-6">
                    <div class="form-group">
                        <label>Address Line 1 </label>
                        <input type="text" class="form-control" />
                    </div>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <div class="form-group">
                        <label>Address Line 2</label>
                        <input type="text" class="form-control" />
                    </div>

                </div>
            </div>
        </div>
        <div class="user-details">
            <div class="row">
                <div class="col-lg-6 col-sm-6">
                    <div class="form-group">
                        <label>Country</label>
                        <select class="form-control">
                            <option>Argentina</option>
                            <option>Australia</option>
                            <option>Austria</option>
                            <option>Belgium</option>
                            <option>Barbados</option>
                            <option>Belarus</option>
                            <option>Bhutan</option>
                            <option>Brazil</option>
                            <option>Cambodia</option>
                            <option>Chile</option>
                            <option>China</option>
                            <option>Columbia</option>
                            <option>Costa Rica</option>
                            <option>Denmark</option>
                            <option>Djibouti</option>
                            <option>Dominican Republic</option>
                            <option>Ecuador</option>
                            <option>Egypt</option>
                            <option>El Salvador</option>
                            <option>Estonia</option>
                            <option>Ethiopia</option>
                            <option>Fiji</option>
                            <option>Finland</option>
                            <option>France</option>
                            <option>Gabon</option>
                            <option>Gambia</option>
                            <option>Georgia</option>
                            <option>Germany</option>
                            <option>Ghana</option>
                            <option>Greece</option>
                            <option>Guatemala</option>
                            <option>Guinea</option>
                            <option>Guyana</option>
                            <option>Haiti</option>
                            <option>Hongkong</option>
                            <option>Hungary</option>
                            <option>Iceland</option>
                            <option>India</option>
                            <option>Indonesia</option>
                            <option>Iran</option>
                            <option>Iraq</option>
                            <option>Ireland</option>
                            <option>Israel</option>
                            <option>Italy</option>
                            <option>Jamaica</option>
                            <option>Japan</option>
                            <option>Jordan</option>
                            <option>Kazakhstan</option>
                            <option>Kenya</option>
                            <option>Korea</option>
                            <option>Kosovo</option>
                            <option>Kuwait</option>
                            <option>Lebanon</option>
                            <option>Liberia</option>
                            <option>Libya</option>
                            <option>Lithuania</option>
                            <option>Luxembourg</option>
                            <option>Macau</option>
                            <option>Malawi</option>
                            <option>Malaysia</option>
                            <option>Mauritius</option>
                            <option>Mexico</option>
                            <option>Micronesia</option>
                            <option>Monaco</option>
                            <option>Mongolia</option>
                            <option>Morocco</option>
                            <option>Nepal</option>
                            <option>New Zealand</option>
                            <option>Netherlands</option>
                            <option>Nigeria</option>
                            <option>Norway</option>
                            <option>Denmark</option>
                            <option>Djibouti</option>
                            <option>Mexico</option>
                            <option>Micronesia</option>
                            <option>Monaco</option>
                            <option>Mongolia</option>
                            <option>Morocco</option>
                            <option>Nepal</option>
                            <option>New Zealand</option>
                            <option>Netherlands</option>
                            <option>Nigeria</option>
                            <option>Norway</option>
                            <option>Pakistan</option>
                            <option>Panama</option>
                            <option>Peru</option>
                            <option>Philippines</option>
                            <option>Poland</option>
                            <option>Portugal</option>
                            <option>Qatar</option>
                            <option>Romania</option>
                            <option>Russia</option>
                            <option>Rwanda</option>
                            <option>South Africa</option>
                            <option>Spain</option>
                            <option>Sri Lanka</option>
                            <option>Switzerland</option>
                            <option>Taiwan</option>
                            <option>Tajikistan</option>
                            <option>Tanzania</option>
                            <option>Thailand</option>
                            <option>Turkey</option>
                            <option>Tuvalu</option>
                            <option>Uganda</option>
                            <option>Ukraine</option>
                            <option>United Arab Emirates</option>
                            <option>United Kingdom</option>
                            <option>United States</option>
                            <option>Venezuela</option>
                            <option>Vietnam</option>
                            <option>Yemen</option>
                            <option>Zimbabwe</option>
                        </select>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-6">
                    <div class="form-group">
                        <label>Phone Number</label>
                        <input type="text" class="form-control" />
                    </div>

                </div>
            </div>
        </div>
        <div class="user-details">
            <div class="row">
                <div class="col-lg-4 col-sm-4">
                    <div class="form-group">
                        <label>State</label>
                        <select class="form-control">
                            <option>Alaska</option>
                            <option>California</option>
                            <option>Colorado</option>
                            <option>Delaware</option>
                            <option>Gerogia</option>
                            <option>Massachusets</option>
                            <option>Nevada</option>
                            <option>New York</option>
                            <option>Ohio</option>
                        </select>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-3">
                    <div class="form-group">
                        <label>City</label>
                        <input type="text" class="form-control" />
                    </div>

                </div>
                <div class="col-lg-5 col-sm-5">
                    <div class="form-group">
                        <label>Zip Code</label>
                        <input type="text" class="form-control" />
                    </div>
                </div>
            </div>
        </div>
        <div class="user-details">
            <div class="row">
                <div class="form-group col-lg-6 col-sm-6">
                    <label>Landmark Nearby</label>
                    <input type="text" class="form-control" />
                </div>
            </div>
        </div>
    </div>
</div>
