<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th style="width: 15px">#</th>
            <th>Name</th>
            <th>Image</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Category</th>
            <th>Option</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($products as $product): ?>
        <tr>
            <td><?php echo ++$i ?></td>
            <td><?php echo $product->getName(); ?></td>
            <td>
                <img src="<?php echo $this->basePath($product->getImage()) ?>" class="image_product">
            </td>
            <td><?php echo $product->getQuantity(); ?></td>
            <td><?php echo $product->getPrice(); ?></td>
            <td>
                <?php if ($product->getCategory() != null){ ?>
                    <a href="<?= $this->url('categories',
                        ['action' => 'view', 'id' => $product->getCategory()->getId()]) ?>">
                        <?php echo $product->getCategory()->getName(); ?>
                    </a>
                <?php } ?>
            </td>
            <td>
                <a href="<?= $this->url('products', ['action' => 'view', 'id' => $product->getId()]) ?>">
                    <i class="glyphicon glyphicon-log-in"></i>
                </a>
                <a href="<?= $this->url('products', ['action' => 'edit', 'id' => $product->getId()]) ?>">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
                <a href="<?= $this->url('products', ['action' => 'delete', 'id' => $product->getId()]) ?>">
                    <i class="glyphicon glyphicon-trash"></i>    
                </a>

            </td>
        </tr>
    <?php endforeach; ?>    
    </tbody>
</table>