<div class="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header">
                <h2 class="box-title">Store's Information</h2>
            </div>
            <div class="box-body">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Name:</th>
                        <td>
                        <?= $this->escapeHtml($store->getName()) ?></th>
                    </tr>
                    <tr>
                        <th>Number of Products:</th>
                        <td>
                        <?= $this->escapeHtml(count($products)) ?></th>
                    </tr>
                    <tr>
                        <th>Phone:</th>
                        <td>
                        <?= $this->escapeHtml($store->getPhone()) ?></th>
                    </tr>
                    <tr>
                        <th>Address:</th>
                        <td>
                        <?= $this->escapeHtml($store->getAddress()) ?></th>
                    </tr>
                    <tr>
                        <th>Date Created:</th>
                        <td>
                        <?= $this->escapeHtml($store->getDateCreated()) ?></th>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
