<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th style="width: 15px">#</th>
            <th>Name</th>
            <th>Address</th>
            <th>Phone</th>
            <th>Number of Product</th>
            <th>Option</th>
        </tr>
    </thead>
    <tbody>
    
    <?php foreach($stores as $store): ?>
        <tr>
            <td>
                <?php echo ++$id; ?>              
            </td>
            <td>
                <?php echo $store->getName(); ?>
            </td>
            <td>
                <?php echo $store->getAddress(); ?>
            </td>
            <td>
                <?php echo $store->getPhone(); ?>
            </td>
            <td>
                <?php echo count($store->getProducts()) ?>
            </td>
            <td>
            
                <a href="<?= $this->url('stores', ['action' => 'view', 'id' => $store->getId()]) ?>">
                    <i class="glyphicon glyphicon-log-in"></i>
                </a>
                <a href="<?= $this->url('stores', ['action' => 'edit', 'id' => $store->getId()]) ?>">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
                <a href="<?= $this->url('stores', ['action' => 'delete', 'id' => $store->getId()]) ?>">
                    <i class="glyphicon glyphicon-trash"></i>    
                </a>

            </td>
        </tr>
    <?php endforeach; ?>    
    </tbody>
</table>