<div class="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header">
                <h2 class="box-title">Store's Information</h2>
            </div>
            <div class="box-body">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Name:</th>
                        <td>
                        <?= $this->escapeHtml($store->getName()) ?></td>
                    </tr>
                    <tr>
                        <th>Number of Products:</th>
                        <td>
                        <?= $this->escapeHtml(count($products)) ?></td>
                    </tr>
                    <tr>
                        <th>Phone:</th>
                        <td>
                        <?= $this->escapeHtml($store->getPhone()) ?></td>
                    </tr>
                    <tr>
                        <th>Address:</th>
                        <td>
                            <?php echo $store->getAddress()->getAddress(); ?>
                            <?php echo $store->getAddress()->getDistrict()->getName(); ?>
                            <?php echo "District" ?>
                            <?php echo $store->getAddress()->getDistrict()->getProvince()->getName(); ?>
                            <?php echo "Province" ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Date Created:</th>
                        <td>
                        <?= $this->escapeHtml($store->getDateCreated()) ?></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
