<?php 
    $form = $this->form; 
    $form->get('submit')->setAttributes([
    'value' => 'Edit',  
    ]);
?>
<h1>Edit Product</h1>
    <div class="row">

        <?= $this->form()->openTag($form); ?>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <?= $this->formLabel($form->get('name')); ?>
                    <?= $this->formElement($form->get('name')); ?>
                    <?= $this->formElementErrors($form->get('name')); ?>                  
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('address')); ?>
                    <?= $this->formElement($form->get('address')); ?>
                    <?= $this->formElementErrors($form->get('address')); ?>                  
                </div>
                <div class="form-group">
                    <?= $this->formLabel($form->get('phone')); ?>
                    <?= $this->formElement($form->get('phone')); ?>
                    <?= $this->formElementErrors($form->get('phone')); ?>                  
                </div>
                
                <?= $this->formElement($form->get('submit')); ?>
            </div> 
        </div>
        <?= $this->form()->closeTag(); ?>
    </div>   
