<div class="box">
    <div class="box-header">
        <h2 clasa="box-title">Stores</h2>
    </div>
    <div class="box-body">
        <?php include_once '_store-table.phtml';?>
    </div>
    <div class="box-footer with-border">
		<a href="<?= $this->url('stores', ['action' => 'add']); ?>" class="btn btn-primary">
            <i class="glyphicon glyphicon-plus"></i>
            <span>Add Store</span>
        </a>
	</div>
</div>
