<div>
    <h2 " class="margin-bottom-20">
        <?php echo 'Products in shop '.$store->getName().' : '?></h2>

    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">

        <thead>
            <tr>
                <th>ID</th>
                <th>Image</th>
                <th>Name</th>
                <th>Option</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($store->getProducts() as $product): ?>
            <tr>
                <td><?php echo ++$i ?></td>
                <td>
                    <img src="<?php echo $this->basePath($product->getImage()) ?>" class="image_product">
                </td>
                <td><?php echo $product->getName(); ?></td>
                <td>
                    <a class="btn btn-warning" href="<?= $this->url('products', ['action'=>'edit','id'=> $product->getId() ]); ?>">Edit</a>
                    <a class="btn btn-danger inline" href="<?= $this->url('products', ['action'=>'delete','id'=> $product->getId() ]); ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>    
        </tbody>
    </table>
</div>
