<div id="listing-page-cart">
    <div class="inner">
        <h1>{{product.name}}</h1>
        <div class="clearfix row">
            <div class="product_details">
                <button type="button" class="btn-secondary pull-right">
                    Ask a Question
                </button>
                <div id="listing-price">${{product.price}}</div>

                <div id="item-stock">
                    <div class="item-stock">
                        {{product.intro}}
                    </div>

                    <div id="item-stock">
                        <label class="property-513">Color: {{selected_color}}</label>
                        <md-button-toggle md-single>
                            <md-button v-for="color in product.colors"
                                       :key="color"
                                       class="color-button margin-button md-raised md-fab md-mini"
                                       :class="{active: color == selected_color}"
                                       :style="{background: color}"
                                       @click="selectColor(color)">
                            </md-button>
                        </md-button-toggle>
                    </div>

                    <div id="item-stock">
                        <label class="property-513">Size: {{product.sizes ? product.sizes[selected_size] : ''}}</label>
                        <md-button-toggle md-single class="md-primary">
                            <md-button v-for="size in product.sizes"
                                       :key="size"
                                       @click.native="selectSize(size)"
                                       class="md-icon-button md-raised margin-button"
                                       :class="{'md-toggle': size == selected_size}">
                                {{size}}
                            </md-button>
                        </md-button-toggle>
                    </div>

                    <div id="item-stock">
                        <md-input-container :class="[errors.has('quantity') ? 'md-input-invalid' : '']">
                            <label>Quantity</label>
                            <md-input type="number"
                                      name="quantity"
                                      v-validate="'required|between:1,100'"
                                      :class="{'is-danger': errors.has('quantity')}"
                                      v-model.number="quantity"></md-input>

                            <span class="md-error"
                                  v-show="errors.has('quantity')">{{errors.first('quantity')}}</span>
                        </md-input-container>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="cart_button" style="padding-top:10px;">
        <button class="btn btn-success btn-block addToCart"
                @click="addToCart">
            Add to cart
        </button>
    </div>
</div>
