<div id="related-listings-container">
    <div id="related-listings-inner">
        <div id="shop-info">
            <h5>Recommended</h5>
<!--            <span>in Sofia, Bulgaria</span>-->
        </div>
        <div id="shop_details">
            <div class="row">
                <div class="col-lg-6">
                    <div class="card">

                        <div class="pull-right hover_icon_outer">
                            <span class="fa fa-heart like_icon red"></span>
                            <span class="fa fa-list like_icon list">
											<span class="glyphicon glyphicon-triangle-bottom"
                                                  style="font-size:10px;"></span>
										</span>
                            <div class="hover_div_outer">
                                <span class="glyphicon glyphicon-triangle-top toparrow_icon"></span>
                                <div class="hover_list">
                                    <p class="text-center list_title">YOUR LIST</P>
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <img src="http://premium-templates.org/ecommerce/html5/curie/demo/images/05pro1.jpg"
                             class="img-responsive">
                        <div class="card-meta">
                            <div class="card-title">
                                Original Illustration Art, acrylic painting, fine art, Judaica
                                wall art, figurative art, original paintings, bible verse wall
                                art, bible art
                            </div>
                            <div class="clearfix">
                                <div class="card-shop pull-left">Cipla</div>
                                <div class="card-price pull-right">US $200</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card">

                        <div class="pull-right hover_icon_outer">
                            <span class="fa fa-heart like_icon red"></span>
                            <span class="fa fa-list like_icon list">
											<span class="glyphicon glyphicon-triangle-bottom"
                                                  style="font-size:10px;"></span>
										</span>
                            <div class="hover_div_outer">
                                <span class="glyphicon glyphicon-triangle-top toparrow_icon"></span>
                                <div class="hover_list">
                                    <p class="text-center list_title">YOUR LIST</P>
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <img src="http://premium-templates.org/ecommerce/html5/curie/demo/images/05pro2.jpg"
                             class="img-responsive">
                        <div class="card-meta">
                            <div class="card-title">
                                Original Illustration Art, acrylic painting, fine art, Judaica
                                wall art, figurative art, original paintings, bible verse wall
                                art, bible art
                            </div>
                            <div class="clearfix">
                                <div class="card-shop pull-left">Cipla</div>
                                <div class="card-price pull-right">US $200</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card">

                        <div class="pull-right hover_icon_outer">
                            <span class="fa fa-heart like_icon"></span>
                            <span class="fa fa-list like_icon list">
											<span class="glyphicon glyphicon-triangle-bottom"
                                                  style="font-size:10px;"></span>
										</span>
                            <div class="hover_div_outer">
                                <span class="glyphicon glyphicon-triangle-top toparrow_icon"></span>
                                <div class="hover_list">
                                    <p class="text-center list_title">YOUR LIST</P>
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <img src="http://premium-templates.org/ecommerce/html5/curie/demo/images/05pro3.jpg"
                             class="img-responsive">
                        <div class="card-meta">
                            <div class="card-title">
                                Original Illustration Art, acrylic painting, fine art, Judaica
                                wall art, figurative art, original paintings, bible verse wall
                                art, bible art
                            </div>
                            <div class="clearfix">
                                <div class="card-shop pull-left">Cipla</div>
                                <div class="card-price pull-right">US $200</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card">

                        <div class="pull-right hover_icon_outer">
                            <span class="fa fa-heart like_icon red"></span>
                            <span class="fa fa-list like_icon list">
											<span class="glyphicon glyphicon-triangle-bottom"
                                                  style="font-size:10px;"></span>
										</span>
                            <div class="hover_div_outer">
                                <span class="glyphicon glyphicon-triangle-top toparrow_icon"></span>
                                <div class="hover_list">
                                    <p class="text-center list_title">YOUR LIST</P>
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <img src="http://premium-templates.org/ecommerce/html5/curie/demo/images/05pro4.jpg"
                             class="img-responsive">
                        <div class="card-meta">
                            <div class="card-title">
                                Original Illustration Art, acrylic painting, fine art, Judaica
                                wall art, figurative art, original paintings, bible verse wall
                                art, bible art
                            </div>
                            <div class="clearfix">
                                <div class="card-shop pull-left">Cipla</div>
                                <div class="card-price pull-right">US $200</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card">

                        <div class="pull-right hover_icon_outer">
                            <span class="fa fa-heart like_icon red"></span>
                            <span class="fa fa-list like_icon list">
											<span class="glyphicon glyphicon-triangle-bottom"
                                                  style="font-size:10px;"></span>
										</span>
                            <div class="hover_div_outer">
                                <span class="glyphicon glyphicon-triangle-top toparrow_icon"></span>
                                <div class="hover_list">
                                    <p class="text-center list_title">YOUR LIST</P>
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <img src="http://premium-templates.org/ecommerce/html5/curie/demo/images/05pro5.jpg"
                             class="img-responsive">
                        <div class="card-meta">
                            <div class="card-title">
                                Original Illustration Art, acrylic painting, fine art, Judaica
                                wall art, figurative art, original paintings, bible verse wall
                                art, bible art
                            </div>
                            <div class="clearfix">
                                <div class="card-shop pull-left">Cipla</div>
                                <div class="card-price pull-right">US $200</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card">

                        <div class="pull-right hover_icon_outer">
                            <span class="fa fa-heart like_icon"></span>
                            <span class="fa fa-list like_icon list">
											<span class="glyphicon glyphicon-triangle-bottom"
                                                  style="font-size:10px;"></span>
										</span>
                            <div class="hover_div_outer">
                                <span class="glyphicon glyphicon-triangle-top toparrow_icon"></span>
                                <div class="hover_list">
                                    <p class="text-center list_title">YOUR LIST</P>
                                    <input type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <img src="http://premium-templates.org/ecommerce/html5/curie/demo/images/04pro1.jpg"
                             class="img-responsive">
                        <div class="card-meta">
                            <div class="card-title">
                                Original Illustration Art, acrylic painting, fine art, Judaica
                                wall art, figurative art, original paintings, bible verse wall
                                art, bible art
                            </div>
                            <div class="clearfix">
                                <div class="card-shop pull-left">Cipla</div>
                                <div class="card-price pull-right">US $200</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>