<div id="related_item">
    <div class="container">
        <div class="row">
            <div class="col-lg-10">
                <p><b>Tags:</b></p>
                <ul>
                    <li>
                        <a href="javascript:void(0);">Clothing</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Unisex Kids' Clothing</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Sweaters</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Childrens Sweater</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Toddler Cardigan</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Toddler Sweater</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Kids Clothes</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Girls Sweater Top</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Unisex Kids Sweater</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Wool Cardigan</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Knit Cardigan</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Wool Sweater</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Kids Fall </a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Childs Clothing</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Childs Fashion</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);">Childs Cardigan</a>
                    </li>
                </ul>
            </div>
        </div><!--row-->
    </div>
</div>