<div class="product_outer" id="product">
    <div id="content">
        <div class="container">
            <div class="wrap white">
                <div class="row clearfix">
                    <div class="col-sm-7">
                        <div class="" id="slider">
                            <?php include_once '_product_images.phtml' ?>
                            <?php include_once '_product_details.phtml' ?>
                        </div>
                    </div>

                    <div class="col-md-5 col-sm-5 col-xs-12">
                        <?php include_once '_product_info.phtml' ?>
                        <?php include_once '_recommend_product.phtml' ?>
                    </div>
                </div>
            </div>
            <?php include_once '_tags.phtml' ?>
        </div><!--container-->

    </div>
</div>