<?php $this->url = $this->basePath() ?>
<div class="body-margin">
    <div id="fh5co-product">
        <div class="container">
            <?php include_once '_product_details.phtml'; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="fh5co-tabs animate-box">
                <ul class="fh5co-tab-nav">
                    <li class="active"><a href="#" data-tab="1">
                            <span class="icon visible-xs"><i class="icon-bar-graph"></i></span>
                            <span class="hidden-xs">Specification</span>
                        </a></li>
                    <li><a href="#" data-tab="2">
                            <span class="icon visible-xs"><i class="icon-star"></i></span>
                            <span class="hidden-xs">Feedback &amp; Ratings</span>
                        </a></li>
                </ul>

                <!-- Tabs -->
                <div class="fh5co-tab-content-wrap">
                    <?php include_once '_product_info.phtml'; ?>
                    <?php include_once '_product_comment_tab.phtml'; ?>
                </div>

            </div>
        </div>
    </div>
</div>
