<div class="content">
    <div id="top-banner-and-menu">
        <div class="container">
            <div class="col-xs-12 col-sm-4 col-md-3 sidemenu-holder">
                <div class="side-menu animate-dropdown">
                    <div class="head"><i class="glyphicon glyphicon-list"></i> danh mục sản phẩm</div>        
                    <nav class="yamm megamenu-horizontal" role="navigation">
                        <ul class="nav">
                            <li class="dropdown menu-item">
                                <a href="#"  class="dropdown-toggle" data-hover="dropdown">IPHONE</a>
                                <ul class="dropdown-menu mega-menu">
                                    <li class="yamm-content">
                                        <div class="row">
                                            <div class="text-center">
                                                <ul class="list-unstyled">
                                                    <li><a href="#">IPHONE 5S|5|5C</a></li>
                                                    <li><a href="#">IPHONE 5S|5|5C</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>  
                                </ul>
                            </li><!-- /.menu-item -->
                        </ul>
                    </nav><!-- /.megamenu-horizontal -->
                </div><!-- /.side-menu -->
                <!-- ================================== TOP NAVIGATION : END ================================== -->     
            </div><!-- /.sidemenu-holder -->
            <div class="slideshow-container col-md-9 col-xs-12 col-sm-8 homebanner-holder">
                    <div id="myCarousel" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel" data-slide-to="1"></li>
                            <li data-target="#myCarousel" data-slide-to="2"></li>
                            <li data-target="#myCarousel" data-slide-to="3"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                              <img src="http://framgiaphone.duocphamhatay.com/upload/slide/iphone.jpg">
                            </div>

                            <div class="item">
                              <img src="http://framgiaphone.duocphamhatay.com/upload/slide/samsung.jpg" >
                            </div>

                            <div class="item">
                              <img src="http://framgiaphone.duocphamhatay.com/upload/slide/xiaomi.png" >
                            </div>

                            <div class="item">
                              <img src="http://framgiaphone.duocphamhatay.com/upload/slide/oppo.jpg">
                            </div>
                        </div>

                        <!-- Left and right controls -->
                        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">sites.previous</span>
                        </a>
                        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">sites.next</span>
                        </a>
                    </div>
                </div>
        </div><!-- /.container -->  
        </div>
    </div>

    <div id="products-tab" class="wow fadeInUp"></div>
    <div id="products" class="wow fadeInUp">
    <div class="container">
        <div class="tab-holder">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" >
                <li class="active"><a href="#featured" data-toggle="tab">sản phẩm nổi bật</a></li>
                <li><a href="#new-arrivals" data-toggle="tab">sản phẩm mới</a></li>
                <li><a href="#top-sales" data-toggle="tab">top giảm giá</a></li>
            </ul>
        </div>
    </div>
</div>