<div class="cart-outer">
    <div class="cart-status">
        <div class="user_content">
            <p class="cart-info">
                <b>Your cart is currently empty</b><br/>
            </p>
            <p class="browse">
                Browse the Shop to find popular sale items<br/>
            </p>
            <a href="/" class="btn btn-primary">Shop Now </a>
        </div>
    </div>
</div>