<div class="row">
    <div class="col-lg-5 col-sm-5">
        <b>Full name: </b>
        {{ order.customer_detail.full_name }}
    </div>
    <div class="col-lg-4 col-sm-4">
        <b>Email: </b>
        {{ order.customer_detail.email }}
    </div>
    <div class="col-lg-3 col-sm-3">
        <b>Phone: </b>
        {{ order.customer_detail.phone_number }}
    </div>
</div>
<div class="row">
    <div class="col-lg-8 col-sm-8">
        <b>Billing address:</b>
        {{ order.customer_detail.address }}
    </div>
</div>

