<div class="panel panel-default">
    <div class="panel-heading">
        People also bought
    </div>
    <div class="panel-body owl_pb" style="">
        <div id="owl-demo2">
            <div class="item"><img src="http://premium-templates.org/ecommerce/html5/darwin/demo/img/macairoh.jpg" alt="img"></div>
            <div class="item"><img src="http://premium-templates.org/ecommerce/html5/darwin/demo/img/sofg.jpg" alt="img"></div>
            <div class="item"><img src="http://premium-templates.org/ecommerce/html5/darwin/demo/img/spacex.jpg" alt="img"></div>
            <div class="item"><img src="http://premium-templates.org/ecommerce/html5/darwin/demo/img/bangolufsen.jpg" alt="img"></div>
            <div class="item"><img src="http://premium-templates.org/ecommerce/html5/darwin/demo/img/bangolf.jpg" alt="img"></div>
        </div>
    </div>
</div>