<div class="panel panel-default">
    <div class="panel-heading">
        Recently Viewed Items
    </div>
    <div class="panel-body owl_pb" style="">
        <div id="owl-demo">
            <div class="item"><img src="http://premium-templates.org/ecommerce/html5/darwin/demo/img/morocteaa.jpg" alt="img"></div>
            <div class="item"><img src="http://premium-templates.org/ecommerce/html5/darwin/demo/img/linidialamp.jpg" alt="img"></div>
            <div class="item"><img src="http://premium-templates.org/ecommerce/html5/darwin/demo/img/bocciawo.jpg" alt="img"></div>
            <div class="item"><img src="http://premium-templates.org/ecommerce/html5/darwin/demo/img/cerealb.jpg" alt="img"></div>
            <div class="item"><img src="http://premium-templates.org/ecommerce/html5/darwin/demo/img/dronec.jpg" alt="img"></div>
            <div class="item"><img src="http://premium-templates.org/ecommerce/html5/darwin/demo/img/jaipblu.jpg" alt="img"></div>
            <div class="item"><img src="http://premium-templates.org/ecommerce/html5/darwin/demo/img/bagh.jpg" alt="img"></div>
        </div>
    </div>
</div>