<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Shopping Mall')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/app/main.css'))
            ->prependStylesheet($this->basePath('css/app/light-blue.css'))
            ->prependStylesheet($this->basePath('css/app/filter.css'))
            ->prependStylesheet($this->basePath('assets/bootstrap/dist/css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('assets/bootstrap/dist/css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('assets/components-font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('assets/animate.css/animate.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/me.js'))
            ->prependFile($this->basePath('assets/bootstrap/dist/js/bootstrap.min.js'))
            ->prependFile($this->basePath('assets/jquery/dist/jquery.min.js'))
            ->prependFile($this->basePath('assets/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js'))
        ?>
    </head>
    <body>
        <div class="wraper">
            <?php include_once 'html/header.php';?>
            <header>
                <?php include_once 'html/search_bar.php';?>
                <?php include_once 'html/nav-bar.php';?>
            </header>
            <div class="row">
                <!-- uncomment code for absolute positioning tweek see top comment in css -->
                <!-- <div class="absolute-wrapper"> </div> -->
                <!-- Menu -->

                <!-- Main Content -->
                <div class="container-fluid">
                    <div class="side-body">
                        <?= $this->content ?>   
                    </div>
                </div>
            </div>

            <?= $this->inlineScript() ?>
            <?php include_once 'html/footer.php';?>
        </div>
    </body>
</html>