<?= $this->doctype() ?>
<html lang="en">
<head>
    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
//        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/app/app.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <!-- IE conditional comments around html tag adds Compat View icon to address bar
        and X-UA-Compatible meta tag is ignored
        https://github.com/h5bp/html5-boilerplate/issues/378 -->
    <!--[if IE 8 ]>

    <title>Infini Shop™ - Mua Sắm Không Giới Hạn</title>


    <link rel="icon" href="http://vn-live-03.slatic.net/homepage/images/2014/icons/favicon-5c48e425ca.png"
          type="image/png"/>
    <!--[if IE]>
    <link rel="shortcut icon" href="http://vn-live-03.slatic.net/homepage/images/2014/icons/favicon.ico"
          type="image/x-icon"/><![endif]-->


    <!--[if !IE]> -->
    <link rel="stylesheet"
          href="http://vn-live-03.slatic.net/homepage/build/desktop-index-b44c795a8a.css"/>
    <!-- <![endif]-->


    <script src="http://vn-live-01.slatic.net/homepage/vendor/scripts/modernizr/modernizr-custom-cc1027d9e8.js"></script>

    <script type="text/javascript">
        var LZD = window.LZD || {};

        LZD.experiments = {};

        // Redesign popup add to cart A/B tests


        // HA-3 Alibaba search A/B tests


        LZD.venture = "vn"; // Possible values: my, vn, sg, ph, th, id
        LZD.lang = "vi";

        LZD.translation = LZD.translation || {};
        LZD.translation['in'] = 'trong';

        LZD.suggestApiUrl = "http://suggest.lazada.vn/";

        LZD.csrfToken = {
            name: "FORM_TOKEN",
            value: "a41163fd472507f85e3852357460b0590f7d6e0d"
        };


        LZD.currency = "VND";
        LZD.richRelevance = {
            "enabled": true,
            "env": "recs",
            "devMode": false,
            "userId": "3ffa7276a0482cd3e0e07f468fdbc1da",
            "userSession": "3ffa7276a0482cd3e0e07f468fdbc1da",
            "apiKey": "5ca037fd95311d50",
            "apiUrl": "//media.richrelevance.com/rrserver/js/1.0/p13n.js",
            "enableBanners": "1",
            "currency": "VND",
            "context": "index",
            "data": {},
            "androidChannelId": "a7db5fdabe9111a7",
            "desktopChannelId": "cd3fa8ca8b35cf0e",
            "iosChannelId": "a23a52942c857c7e",
            "mobileChannelId": "a12f9573b3231bcc",
            "operaMiniChannelId": "1e168d1b4d6327cf"
        };
        LZD.taobao = {};
        LZD.extraInfo = {"customerId": "7d2794d5-9050-4ffc-5c01-a338375069ba"};
        LZD.dataScience = {
            "apiUrl": "https://recommender.lazada.vn/rico_client.js",
            "env": {
                "apiEndpoint": "https://recommender.lazada.vn",
                "apiKey": "03e3b55b-cdb1-4a44-8f7e-79bfcc510a33",
                "clientID": "lzdMy",
                "currency": "VND",
                "venture": "VN"
            }
        }

        var JS_ERRORS_DISABLE = 1;

        if (typeof console === "undefined" || typeof console.log === "undefined") {
            console = {};
            console.log = function () {
            };
        }
    </script>


    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>

</head>
<body class="" data-control="Home" data-qa-theme-locator="theme-desktop" data-qa-page-locator="homepage"
      data-js-component="user-scroll" data-spm="home">
<div class="c-sticker " data-js-component="sticker"
     style="z-index: 3"
     data-js-component-params='{


        "fixPlaceholderHeight": true,

}'>
    <div class="c-sticker__body">
        <div class="c-sticker__content">

            <header class="c-header " data-js-component="header" data-js-component-params="{
        showNavText: 'Tất cả danh mục',
        hideNavText: 'Ẩn danh mục ngành hàng',
        taobao: false
    }">


                <div class="c-header__links-bar">
                    <nav class="c-top-bar">
                        <ul class="c-top-bar__list">
                            <li class="c-top-bar__item">
                                <div class="c-dropdown
    c-dropdown_theme_
    c-dropdown_align_center
    c-dropdown_valign_bottom
    c-dropdown_toggler_yes

"
                                     data-qa-locator="header-get-the-app"
                                     data-js-component="dropdown"
                                     data-js-component-params='{
        openOnHover: false,
        closeButton: false,
        closeOnClick: true,
        noToggler: false,
        isOpened: false
    }'>


                                    <div class="c-dropdown__popup">
                                        <div class="c-dropdown__content">

                                            <!-- start cms-block download-the-app-by-phone_vi (rev. 20) -->
                                            <style>
                                                .dropdown_theme_elegant .dropdown__toggle_text-color_orange {
                                                    cursor: pointer;
                                                }
                                            </style>

                                            <script>
                                                $('.header .dropdown__toggle_text-color_orange').removeClass('dropdown__toggle');
                                                $(document.body).on('click', '.header .dropdown__toggle_text-color_orange', function (e) {
                                                    window.location.href = 'https://www.lazada.vn/promo-mobile-apps/';
                                                });
                                                $('.c-header .c-top-bar__item:first-child div').removeClass('c-dropdown');
                                                $(document.body).on('click', '.c-header .c-top-bar__item-caption_color_orange', function (e) {
                                                    window.location.href = 'https://www.lazada.vn/promo-mobile-apps/';
                                                });
                                            </script>
                                            <!-- end cms-block download-the-app-by-phone_vi (rev. 20) -->

                                        </div>

                                    </div>
                                </div>

                            </li>

                            <li class="c-top-bar__item js-header-order-tracking">
                                <div class="c-dropdown
    c-dropdown_theme_
    c-dropdown_align_center
    c-dropdown_valign_bottom
    c-dropdown_toggler_yes

"
                                     data-qa-locator="header-track-my-order"
                                     data-js-component="dropdown"
                                     data-js-component-params='{
        openOnHover: false,
        closeButton: false,
        closeOnClick: true,
        noToggler: false,
        isOpened: false
    }'>

    <span class="c-dropdown__caption">

                        <span class="c-top-bar__item-caption">
                            Kiểm tra đơn hàng
                        </span>

    </span>
                                    <div class="c-dropdown__popup">
                                        <div class="c-dropdown__content">

                                            <div class="c-order-tracking-form  "
                                                 data-js-component="order-tracking-form">


                                                <form class="c-order-tracking-form__form" id="order_tracking"
                                                      action="/index/viewOrderTracking" method="get">
                                                    <div class="c-order-tracking-form__title">Kiểm tra đơn hàng</div>

                                                    <div class="c-order-tracking-form__form-row">
                                                        <label for="email" class="c-order-tracking-form__label">Vui lòng
                                                            nhập địa chỉ email:</label>
                                                        <input class="c-order-tracking-form__input c-order-tracking-form__email"
                                                               type="text" name="email" value="" id="email"/>
                                                    </div>

                                                    <div class="c-order-tracking-form__form-row">
                                                        <label for="orderNr" class="c-order-tracking-form__label">Vui
                                                            lòng nhập mã đơn hàng:</label>
                                                        <div class="c-order-tracking-form__input-group">
                                                            <input class="c-order-tracking-form__input c-order-tracking-form__order"
                                                                   type="text" name="orderNr" value="" id="orderNr"
                                                                   placeholder="Ví dụ: 123456789"/>
                                                            <span class="c-order-tracking-form__button-container">

                    <button class="c-order-tracking-form__button" id="btn-get-order-tracking-data" type="submit">
                            <i class="c-order-tracking-form__icon"></i>
                    </button>
                </span>
                                                        </div>
                                                    </div>
                                                    <p class="c-order-tracking-form__help-text">
                                                        Nếu bạn có thắc mắc nào khác, <a
                                                                href="#"><a
                                                                    href="#"
                                                                    target="_blank">Nhấn vào đây</a></a>
                                                    </p>
                                                    <p class="c-order-tracking-form__status"></p>
                                                </form>
                                            </div>


                                        </div>

                                    </div>
                                </div>

                            </li>

                            <?php if ($this->user == null) { ?>
                                <li class="c-top-bar__item " data-qa-locator="header-login">

                                    <a class="c-top-bar__item-caption" href="/login">Đăng nhập</a>

                                </li>
                                <li class="c-top-bar__item " data-qa-locator="header-signup">

                                    <a class="c-top-bar__item-caption" href="/register">Đăng ký</a>

                                </li>

                            <?php } else { ?>
                                <li class="c-top-bar__item">
                                    <div class="c-dropdown
    c-dropdown_theme_
    c-dropdown_align_center
    c-dropdown_valign_bottom
    c-dropdown_toggler_yes

"
                                         data-qa-locator="header-customer-care"
                                         data-js-component="dropdown"
                                         data-js-component-params='{
        openOnHover: false,
        closeButton: false,
        closeOnClick: false,
        noToggler: false,
        isOpened: false
    }'>

    <span class="c-dropdown__caption">

                        <span class="c-top-bar__item-caption">
                            <?php echo $this->user['name'] ?>
                            <span class="caret"></span>
                        </span>

    </span>

                                        <div class="c-dropdown__popup">
                                            <div class="c-dropdown__content">


                                                <ul class="dropdown__items">
                                                    <!-- start cms-block header-customer-care_vi (rev. 1256) -->
                                                    <li class="dropdown__item">
                                                        <a href="/user/view" class="dropdown__item-anchor"><span
                                                                    class="dropdown__item-icon"><i
                                                                        class="icon icon-customer-care-help-centre"></i></span>
                                                            Quản lý tài khoản</a>
                                                    </li>
                                                    <li class="dropdown__item">
                                                        <a href="#" class="dropdown__item-anchor"><span
                                                                    class="dropdown__item-icon"><i
                                                                        class="icon icon-customer-care-order-payment"></i></span>
                                                            Đơn hàng của tôi </a>
                                                    </li>
                                                    <li class="dropdown__item">
                                                        <a href="/logout" class="dropdown__item-anchor"><span
                                                                    class="dropdown__item-icon"><i
                                                                        class="icon icon-customer-care-shipping-delivery"></i>  </span>Đăng
                                                            xuất</a>
                                                    </li>

                                                    <!-- end cms-block header-customer-care_vi (rev. 1256) -->
                                                </ul>

                                            </div>

                                        </div>
                                    </div>

                                </li>
                            <?php } ?>
                        </ul>
                    </nav>

                </div>
                <div class="c-header__content">

                    <a href="/" class="c-logo c-header__logo" data-qa-locator="header-logo">
                        <div class="nav_logo">
                            <h1 class="logo">
                                <span class="word1">Infini</span>
                                <span class="word2">Shop</span>
                            </h1>
                        </div>
                    </a>


                    <div class="c-header__search">
                        <div class="c-header-search"
                             data-js-component="header-search"
                             data-js-component-params="{
        searchContext: null
    }"
                        >
                            <form class="c-header-search__form" action="#" method="get"
                                  autocomplete="off">
                                <div>
                                    <div class="c-header-search__input-group">
                                        <div class="c-header-search__input-group-input">
                                            <input class="c-header-search__input-group-textbox c-header-search__input-group-textbox_search"
                                                   type="search"
                                                   placeholder="Tìm kiếm sản phẩm, thương hiệu hay nhãn hàng mong muốn …"
                                                   value=""
                                                   name="q"
                                                   data-qa-locator="header-searchbar"
                                            />
                                            <input class="c-header-search__input-group-textbox c-header-search__input-group-textbox_hint"
                                                   type="text"
                                                   disabled="disabled"
                                                   autocomplete="off"
                                                   tabindex="-1"
                                                   value=""
                                            />
                                        </div>

                                        <div class="c-header-search__input-group-button-container">
                                            <button type="submit"
                                                    class="c-header-search__input-group-button c-header-search__input-group-button_type_search"
                                                    data-qa-locator="header-search-button">
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <div class="c-header-search__results">
                                <div class="c-header-search__suggestion-menu" id="searchSuggestResult"></div>
                            </div>
                            <div class="c-header-search__popular-result">
                                <div class="c-header-search__popular-search">
                                    <span class="c-header-search__popular-search-title">Xu hướng tìm kiếm</span>
                                    <ul class="c-header-search__popular-search-list">
                                        <!-- start cms-block popular-search-tags_vi (rev. 747) -->
                                        <li class="" popular-search__item
                                        ""><a class="" popular-search__item-anchor""
                                        href="#"
                                        onclick="_gaq.push(['_trackEvent', 'LZD', 'LZD_Popular_Search',
                                        'Clicks_Popular_Search_01']);">Ưu đãi</a></li>

                                        <li class="" popular-search__item
                                        ""><a class="" popular-search__item-anchor""
                                        href="#"
                                        onclick="_gaq.push(['_trackEvent', 'LZD', 'LZD_Popular_Search',
                                        'Clicks_Popular_Search_03']);">Zara</a></li>

                                        <li class="" popular-search__item
                                        ""><a class="" popular-search__item-anchor""
                                        href="#"
                                        onclick="_gaq.push(['_trackEvent', 'LZD', 'LZD_Popular_Search',
                                        'Clicks_Popular_Search_05']);">Áo ba lỗ</a></li>


                                        <li class="" popular-search__item
                                        ""><a class="" popular-search__item-anchor""
                                        href="#"
                                        onclick="_gaq.push(['_trackEvent', 'LZD', 'LZD_Popular_Search',
                                        'Clicks_Popular_Search_06']);">Quần què</a></li>
                                        <!-- end cms-block popular-search-tags_vi (rev. 747) -->
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="c-header__basket">
                        <a href="/cart" class="c-cart-button c-cart-button_empty"
                           data-qa-locator="header-cart" data-js-component="cart-button">
                            <span class="c-cart-button__icon"></span>
                            <span class="c-cart-button__num">0</span>
                        </a>
                    </div>


                    <span class="c-header__navigation-toggle">

                    Tất cả danh mục

            </span>

                </div>
                <footer class="c-header__bottom-bar">


                    <div class="c-header__main-navigation">
                        <div class="c-main-navigation  " data-js-component="main-navigation">
                            <div class="c-main-navigation__nav-wrapper">
                                <nav class="c-main-navigation__nav">

                                    <span
                                                class="c-main-navigation__item c-main-navigation__item_style_default c-main-navigation__item_type_button"
                                        >
                    <span class="c-main-navigation__item-caption">
                        <a href="#">Thời trang nam</a>
                    </span>
                </span>


                                    <span
                                            class="c-main-navigation__item c-main-navigation__item_style_default c-main-navigation__item_type_button"
                                            data-id="3"
                                            data-tracking-nav-header="Thời trang">
                    <span class="c-main-navigation__item-caption">
                        <a href="#">Thời trang nữ</a>
                    </span>
                </span>

                                    <span
                                            class="c-main-navigation__item c-main-navigation__item_style_default c-main-navigation__item_type_button"
                                            data-id="4"
                                            data-tracking-nav-header="Đồng hồ &amp; Phụ Kiện ">
                    <span class="c-main-navigation__item-caption">
                        <a href="#">Thời trang trẻ em</a>
                    </span>
                </span>

                                    <span
                                            class="c-main-navigation__item c-main-navigation__item_style_default c-main-navigation__item_type_button"
                                            data-id="5"
                                            data-tracking-nav-header="Nhà cửa &amp; Đời sống">
                    <span class="c-main-navigation__item-caption">
                        <a href="#">Mùa xuân</a>
                    </span>
                </span>

                                    <span
                                            class="c-main-navigation__item c-main-navigation__item_style_default c-main-navigation__item_type_button"
                                            data-id="6"
                                            data-tracking-nav-header="Sức khỏe &amp; Sắc đẹp">
                    <span class="c-main-navigation__item-caption">
                        <a href="#">Mùa hạ</a>
                    </span>
                </span>

                                    <span
                                            class="c-main-navigation__item c-main-navigation__item_style_default c-main-navigation__item_type_button"
                                            data-id="7"
                                            data-tracking-nav-header="Trẻ em &amp; Đồ chơi">
                    <span class="c-main-navigation__item-caption">
                        <a href="#">Mùa thu</a>
                    </span>
                </span>

                                    <span
                                            class="c-main-navigation__item c-main-navigation__item_style_default c-main-navigation__item_type_button"
                                            data-id="11"
                                            data-tracking-nav-header="Bách hóa gia đình">
                    <span class="c-main-navigation__item-caption">
                        <a href="#">Mùa đông</a>
                    </span>
                </span>

                                    <!--                                    <span-->
                                    <!--                                            class="c-main-navigation__item c-main-navigation__item_style_default c-main-navigation__item_type_button"-->
                                    <!--                                            data-id="8"-->
                                    <!--                                            data-tracking-nav-header="Thể thao &amp; Du lịch">-->
                                    <!--                    <span class="c-main-navigation__item-caption">-->
                                    <!--                        Thể thao &amp; Du lịch-->
                                    <!--                    </span>-->
                                    <!--                </span>-->
                                    <!---->
                                    <!--                                    <span-->
                                    <!--                                            class="c-main-navigation__item c-main-navigation__item_style_default c-main-navigation__item_type_button"-->
                                    <!--                                            data-id="9"-->
                                    <!--                                            data-tracking-nav-header="Xe máy, Sách &amp; Dịch vụ">-->
                                    <!--                    <span class="c-main-navigation__item-caption">-->
                                    <!--                        Xe máy, Sách &amp; Dịch vụ-->
                                    <!--                    </span>-->
                                    </span>

                                    <span
                                            class="c-main-navigation__item c-main-navigation__item_style_bold-orange c-main-navigation__item_type_button"
                                            data-id="10"
                                            data-tracking-nav-header="Khuyến mãi &amp; Hàng hiệu">
                    <span class="c-main-navigation__item-caption">
                        <a href="#">Khuyến mãi</a>
                    </span>
                </span>

                                </nav>
                            </div>

                            <div class="c-main-navigation__second-menu-wrapper" data-js-component-lazy-init="true">
                                <div class="c-main-navigation__second-menu">

                                </div>
                            </div>

                        </div>

                    </div>


                </footer>


                <ul class="c-notifier"
                    data-js-component="notifier"
                    data-js-component-params='{
        "messages": [

        ]
    }'>
                </ul>

            </header>

        </div>
    </div>
</div>

<?= $this->content ?>


<footer class="c-footer">

    <section class="c-footer__section c-footer__section_one">
        <div class="c-footer__section-inner">
            <div class="c-footer__block c-footer__block_newsletter-app-download">
                <div class="c-footer__block c-footer__block_app-download">
                    <!-- start cms-block footer-2015-app-download_vi (rev. 11) -->
                    <div class="footer-app-download__text-block">
                        <div class="footer-app-download__title">"MUA SẮM THEO CÁCH CỦA BẠN</div>
                        <div class="footer-app-download__text">Tính tiền theo cách của chúng tôi"</div>
                        <div style="text-align: left;color: white;overflow: hidden;float: none;width: 100%;padding-top: 15px;">
                            \> Infini Shop 2017
                        </div>
                    </div>


                    <!-- end cms-block footer-2015-app-download_vi (rev. 11) -->
                </div>
            </div>
        </div>
    </section>


</footer>
<script src="http://vn-live-01.slatic.net/homepage/build/desktop-index-fcc46c9f85.js"></script>
<?= $this->inlineScript() ?>
</body>
</html>
