<?php
    function status_class($id) {
        if($id == 1) return "bg-red";
        if($id == 2) return "bg-blue";
        if($id == 3) return "bg-yellow";
    }

    function status_content($id) {
        if($id == 1) return "pending";
        if($id == 2) return "shipping";
        if($id == 3) return "completed";
    }
?>
<div class="box-body">

    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Index</th>
                <th>User</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Items</th>
                <th>Cost</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($orders as $order): ?>
            <tr>
                <td><?php echo ++$i ?></td>
                <?php 
                    if($order->getUser == null)
                        echo "<td>".$order->getName()."</td>";
                    else
                        echo '<td><a href="#">'.$order->getName()."</a></td>";
                ?>
                <td><?php echo $order->getPhone(); ?></td>
                <td><?php echo $order->getAddress(); ?></td>
                <td><?php echo $order->getNumberOfItems(); ?></td>
                <td><?php echo $order->getCost(); ?></td>
                <td>
                    <small class="label <?php echo status_class($order->getStatus())?>">
                        <?php echo status_content($order->getStatus()); ?>
                    </small>
                </td>
                <td>
                    <a href="">
                        <i class="glyphicon glyphicon-eye-open"></i>
                    </a>
                    <a href="<?= $this->url('orders', ['action' => 'edit', 'id' => $order->getId()]) ?>">
                        <i class="fa fa-truck"></i>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>    
        </tbody>
	</table>
</div>
