<?php
    function status_class($id) {
        if($id == 1) return "bg-red";
        if($id == 2) return "bg-blue";
        if($id == 3) return "bg-yellow";
    }

    function status_content($id) {
        if($id == 1) return "pending";
        if($id == 2) return "shipping";
        if($id == 3) return "completed";
    }
?>
<h1 class="text-center">Order View</h1>
<br>
<div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-6">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">User's Informations</h3>
            </div>
            <div class="box-body no-padding">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Name:</th>
                        <td>
                            <?php 
                                if($order->getUser() == null)
                                    echo $order->getName();
                                else
                                    echo "<a href=\"{$this->url('users', ['action' => 'view', 'id' => $order->
                                        getUser()->getId()])}\">".$order->getName()."</a>";
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Phone:</th>
                        <td>
                        <?= $this->escapeHtml($order->getPhone()) ?></td>
                    </tr>
                    <tr>
                        <th>Address:</th>
                        <td>
                        <?= $this->escapeHtml($order->getFullAddress()) ?></td>
                    </tr>
                </table>
            </div>
        </div>
        
    </div>
</div>
<br>
<?php include_once '_order-info.phtml' ?>