<div class="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header">
                <h2 class="box-title">Category's Information</h2>
            </div>
            <div class="box-body">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Name:</th>
                        <td>
                        <?= $this->escapeHtml($category->getName()) ?></th>
                    </tr>
                    <tr>
                        <th>Number of Products:</th>
                        <td>
                        <?= $this->escapeHtml(count($category->getProducts())) ?></th>
                    </tr>
                    <tr>
                        <th>Description:</th>
                        <td>
                        <?= $this->escapeHtml($category->getDescription()) ?></th>
                    </tr>
                    <tr>
                        <th>Date Created:</th>
                        <td>
                        <?= $this->escapeHtml($category->getDateCreated()) ?></th>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
