<div class="box-body">
    <a href="<?= $this->url('products', ['action' => 'add']); ?>" class="btn btn-primary margin-bottom-20">
        Tạo Mới</a>

    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Index</th>
                <th>Name</th>
                <th>Description</th>
                <th>Option</th>
            </tr>
        </thead>
        <tbody>
            <?php $i = 1 ?>
            <?php foreach($categories as $category): ?>
                <tr>
                    <td><?php echo $i++ ?></td>
                    <td><?php echo $category->getName() ?></td>
                    <td><?php echo truncate($category->getDescription(), 30) ?></td>
                    </td>
                    <td><a class="btn btn-primary" href="<?= $this->url('categories',
                            ['action' => 'view', 'id' => $category->getId()]) ?>">Show</a>
                        <a class="btn btn-warning" href="<?= $this->url('categories',
                            ['action' => 'edit', 'id' => $category->getId()]) ?>">Edit</a>
                        <a class="btn btn-danger" href="<?= $this->url('categories',
                            ['action' => 'delete', 'id' => $category->getId()]) ?>">Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<!-- /.box-body -->
</div>

<?php
    function truncate($text, $chars = 25) {
        if (strlen($text) > $chars){
            $text = $text." ";
            $text = substr($text,0,$chars);
            $text = $text."...";
        }
        return $text;
    }
?>
