<h1>View Category</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Name:</th>
                <td>
                <?= $this->escapeHtml($category->getName()) ?></th>
            </tr>
            <tr>
                <th>Description:</th>
                <td>
                <?= $this->escapeHtml($category->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td>
				<?= $this->escapeHtml($category->getDateCreated()) ?></th>
            </tr>
         </table>
    </div>
</div>
<br>
<div class="box-body">
    <h2 " class="margin-bottom-20">
        <?php echo 'Products in category '.$category->getName().' : '?></h2>

    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">

        <thead>
            <tr>
                <th>ID</th>
                <th>Image</th>
                <th>Name</th>
                <th>Option</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($category->getProducts() as $product): ?>
            <tr>
                <td><?php echo ++$i ?></td>
                <td>
                    <img src="<?php echo $this->basePath($product->getImage()) ?>" class="image_product">
                </td>
                <td><?php echo $product->getName(); ?></td>
                <td>
                    <a class="btn btn-warning" href="<?= $this->url('products', ['action'=>'edit','id'=> $product->getId() ]); ?>">Edit</a>
                    <a class="btn btn-danger inline" href="<?= $this->url('products', ['action'=>'delete','id'=> $product->getId() ]); ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>    
        </tbody>
    </table>
</div>