<h1>View Category</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Name:</th>
                <td>
                <?= $this->escapeHtml($category->getName()) ?></th>
            </tr>
            <tr>
                <th>Description:</th>
                <td>
                <?= $this->escapeHtml($category->getDescription()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td>
				<?= $this->escapeHtml($category->getDateCreated()) ?></th>
            </tr>
         </table>
    </div>
</div>