<?php
$this->headTitle('Register');

// $this->mainMenu()->setActiveItemId('users');
//
//$this->pageBreadcrumbs()->setItems([
//    'Home' => $this->url('home'),
//    'Manage Users' => $this->url('users'),
//    'Add User' => $this->url('users', ['action' => 'add'])
//]);

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'email@example.com'
]);

$form->get('full_name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'John Doe'
]);

$form->get('address')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'So 3, Dai Co Viet, Hai Ba Trung, Ha Noi'
]);

$form->get('phone')->setAttributes([
    'class' => 'form-control',
    'placeholder' => ''
]);

//$form->get('status')->setAttributes([
//    'class' => 'form-control'
//]);

$form->get('password')->setAttributes([
    'class' => 'form-control'
]);

$form->get('confirm_password')->setAttributes([
    'class' => 'form-control'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);

$form->prepare();
?>

<h1>Register</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('full_name')); ?>
            <?= $this->formElement($form->get('full_name')); ?>
            <?= $this->formElementErrors($form->get('full_name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_password')); ?>
            <?= $this->formElement($form->get('confirm_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('address')); ?>
            <?= $this->formElement($form->get('address')); ?>
            <?= $this->formElementErrors($form->get('address')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('phone')); ?>
            <?= $this->formElement($form->get('phone')); ?>
            <?= $this->formElementErrors($form->get('phone')); ?>
        </div>


        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>   

