<?php
$this->headTitle('Edit User');

//$this->mainMenu()->setActiveItemId('users');
//
//$this->pageBreadcrumbs()->setItems([
//    'Home' => $this->url('home'),
//    'Manage Users' => $this->url('users'),
//    'Edit User' => $this->url('users', ['action' => 'edit', 'id' => $user->getId()])
//]);

$form->get('full_name')->setAttributes([
    'class' => 'form-control',
]);

$form->get('address')->setAttributes([
    'class' => 'form-control',
]);

$form->get('phone')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')
    ->setAttributes(['class' => 'btn btn-primary'])
    ->setValue('Save');

$form->prepare();
?>

<div class="row">
    <div class="col-md-4 col-md-offset-4 register">
        <div class="register-form">
            <h2>Edit your profile</h2>

            <?= $this->form()->openTag($form); ?>

            <div class="form-group">
                <?= $this->formLabel($form->get('full_name')); ?>
                <?= $this->formElement($form->get('full_name')); ?>
                <?= $this->formElementErrors($form->get('full_name')); ?>
            </div>
            <div class="form-group">
                <?= $this->formLabel($form->get('province')); ?>
                <?= $this->formElement($form->get('province')); ?>
                <?= $this->formElementErrors($form->get('province')); ?>                  
            </div>
            <div class="form-group">
                <?= $this->formLabel($form->get('district')); ?>
                <?= $this->formElement($form->get('district')); ?>
                <?= $this->formElementErrors($form->get('district')); ?>                  
            </div>
            <div class="form-group">
                <?= $this->formLabel($form->get('address')); ?>
                <?= $this->formElement($form->get('address')); ?>
                <?= $this->formElementErrors($form->get('address')); ?>                  
            </div>
            <div class="form-group">
                <?= $this->formLabel($form->get('phone')); ?>
                <?= $this->formElement($form->get('phone')); ?>
                <?= $this->formElementErrors($form->get('phone')); ?>
            </div>

            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
