<?php
$this->headTitle('Reset Password');

$form->get('email')->setAttributes([
    'class' => 'form-control',
]);

$form->get('captcha')->setAttributes([
    'class' => 'form-control',
]);

$form->get('submit')->setAttributes([
    'class' => 'btn btn-large btn-primary'
]);

$form->prepare();
?>

<div class="row">
    <div class="col-md-4 col-md-offset-4 register">
        <div class="register-form">
            <h2>Reset Password</h2>

            <?= $this->form()->openTag($form); ?>

            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>

            <?= $this->formElement($form->get('captcha')); ?>
            <p class="hint">Enter the letters above as you see them.</p>

            <?= $this->formElement($form->get('submit')); ?>

            <?= $this->formElement($form->get('csrf')); ?>

            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
