<?php
$this->headTitle('View User');

// $this->mainMenu()->setActiveItemId('users');

//$this->pageBreadcrumbs()->setItems([
//    'Home' => $this->url('home'),
//    'Manage Users' => $this->url('users'),
//    'View User' => $this->url('users', ['action' => 'view', 'id' => $user->getId()])
//]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>User Profile</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>E-mail:</th>
                <td>
                <?= $this->escapeHtml($user->getEmail()) ?></th>
            </tr>
            <tr>
                <th>Name:</th>
                <td>
                <?= $this->escapeHtml($user->getName()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td>
                <?= $this->escapeHtml($user->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th>Address:</th>
                <td>
                <?= $this->escapeHtml($user->getAddress()) ?></th>
            </tr>
            <tr>
                <th>Phone:</th>
                <td>
                <?= $this->escapeHtml($user->getPhone()) ?></th>
            </tr>
        </table>
        <a class="btn btn-info" href="<?= $this->url('user',
            ['action' => 'edit']); ?>">
            <span class="glyphicon glyphicon-pencil"></span> Edit
        </a>
        <a class="btn btn-default" href="<?= $this->url('user',
            ['action' => 'change-password']); ?>">
            <span class="glyphicon glyphicon-asterisk"></span> Change Password
        </a>
    </div>
</div>
