<svg height="5" width="200">
<line x1="0" y1="0" x2="200" y2="0" style="stroke:#004165;stroke-width:5" />
    Sorry, your browser does not support inline SVG.
</svg>

<div class="event1">
    <div class="event1Bubble">
        <div class="eventTime">
            <div class="DayDigit"><?php echo $saleProgram->getDateStart() ?></div>
        </div>
        <div class="eventTitle">Date Start</div>
    </div>

    <svg height="20" width="20">
        <circle cx="10" cy="11" r="5" fill="#004165" />
    </svg>    
</div>
