<svg height="5" width="150">
    <line x1="0" y1="0" x2="150" y2="0" style="stroke:rgba(162, 164, 163, 0.37);stroke-width:5" />
        Sorry, your browser does not support inline SVG.
</svg>
<div class="event3 futureGray ">
    <div class="event1Bubble futureOpacity">
        <div class="eventTime">
            <div class="DayDigit"><?php echo $saleProgram->getDateEnd() ?></div>
        </div>
        <div class="eventTitle">Date Start</div>
    </div>
    <svg height="20" width="20">
        <circle cx="10" cy="11" r="5" fill="rgba(162, 164, 163, 0.37)" />
    </svg>
</div>
