<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Image</th>
            <th>Category</th>
            <th style="width: 12px">Option</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($products as $product): ?>
        <tr>
            <td id="name-<?php echo $product->getID() ?>"><?php echo $product->getName(); ?></td>
            <td>
                <img src="<?php echo $this->basePath($product->getImage()) ?>" class="image_product">
            </td>
            <td><?php echo $product->getCategory()->getName(); ?></td>
            <td>
                <button id="<?php echo $product->getID() ?>" class="btn btn-primary btn-sm btn-add"
                    data-toggle="modal" data-target="#modal-info">Add</button>
            </td>
        </tr>
    <?php endforeach; ?>    
    </tbody>
</table>
