<table id="example-1" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Image</th>
            <th>Color</th>
            <th>Category</th>
            <th>Sale</th>
            <th style="width: 12px">Option</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($products_in_sale as $product): ?>
        <tr id="row-<?php echo $product->getID() ?>">
            <td id="name-<?php echo $product->getID() ?>"><?php echo $product->getName(); ?></td>
            <td>
                <img src="<?php echo $this->basePath($product->getImage()) ?>" class="image_product">
            </td>
            <td>
                <?php foreach ($product->getColors() as $c) { ?>
                        <i class="set-size-icon pull-right color-<?php echo $c ?>" >
                            <p class="hidden"><?php echo $list_color[$c] ?></p>
                        </i>
                <?php } ?>
            </td>
            </td>
            <td>
                <?php if ($product->getCategory() != null){ ?>
                    <a href="<?= $this->url('categories',
                        ['action' => 'view', 'id' => $product->getCategory()->getId()]) ?>">
                        <?php echo $product->getCategory()->getName(); ?>
                    </a>
                <?php } ?>
            </td>
            <td>
                <span class="label bg-yellow">
                    <?php echo $sale_array[$product->getId()] ?>%
                </span>
            </td>
            <td>
                <form action="<?= $this->url('sale_programs', ['action' => 'removeproduct']) ?>"
                    method="POST" class="remove-form" id="form-<?php echo $product->getId() ?>" title="remove">
                    <input type="hidden" name="sale_program_id" value="<?php echo $saleProgram->getId() ?>">
                    <input type="hidden" name="product_id" value="<?php echo $product->getId() ?>">                        
                    <button type="submit" class="btn btn-sm btn-danger" title="remove">
                        <i class="fa fa-close"></i>
                    </button>
                </form>
            </td>
        </tr>
    <?php endforeach; ?>    
    </tbody>
</table>
