<div class="row">
    <div class="col-md-6">
        <div class="box">
            <div class="box-header">
                <h2 class="box-title">Sale Program's Information</h2>
            </div>
            <div class="box-body">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Name:</th>
                        <td>
                        <?= $this->escapeHtml($saleProgram->getName()) ?></td>
                    </tr>
                    <tr>
                        <th>Date Start:</th>
                        <td>
                        <?= $this->escapeHtml($saleProgram->getDateStart()) ?></td>
                    </tr>
                    <tr>
                        <th>Address:</th>
                        <td>
                            <?php echo $saleProgram->getDateEnd(); ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Date Created:</th>
                        <td>
                        <?= $this->escapeHtml($saleProgram->getDateCreated()) ?></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
