<div class="Timeline">
    <?php if ($saleProgram->getCurrentStatus() == 2) {?>
        <?php include_once '_date-start-before.phtml';?> 
        <?php include_once '_date-end-before.phtml';?> 
    <?php } ?>

    <?php if ($saleProgram->getCurrentStatus() == 0) {?>
        <?php include_once '_date-start-before.phtml';?> 
    <?php } ?>

    <svg height="5" width="200">
        <line x1="0" y1="0" x2="200" y2="0" style="stroke:#004165;stroke-width:5" />
            Sorry, your browser does not support inline SVG.
    </svg>

    <div class="now" title="<?php echo $currentDate ?>">
        TODAY
    </div>

    <?php if ($saleProgram->getCurrentStatus() == 0) {?>
        <?php include_once '_date-end-after.phtml';?> 
    <?php } ?> 

    <?php if ($saleProgram->getCurrentStatus() == 1) {?>
        <?php include_once '_date-start-after.phtml';?> 
        <?php include_once '_date-end-after.phtml';?>
    <?php } ?> 
    
    <svg height="5" width="50">
        <line x1="0" y1="0" x2="50" y2="0" style="stroke:#004165;stroke-width:5" /> 
    </svg>

    <svg height="20" width="42">
        <line x1="1" y1="0" x2="1" y2="20" style="stroke:#004165;stroke-width:2" /> 
        <circle cx="11" cy="10" r="3" fill="#004165" />  
        <circle cx="21" cy="10" r="3" fill="#004165" />  
        <circle cx="31" cy="10" r="3" fill="#004165" />    
        <line x1="41" y1="0" x2="41" y2="20" style="stroke:#004165;stroke-width:2" /> 
    </svg> 
</div>
