<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Add New Sale Program</h3>
            </div>
            <?= $this->form()->openTag($form); ?>
                <div class="box-body">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('name')); ?>
                        <?= $this->formElement($form->get('name')); ?>
                        <?= $this->formElementErrors($form->get('name')); ?>                
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($form->get('date_start')); ?>
                        <?= $this->formElement($form->get('date_start')); ?>
                        <?= $this->formElementErrors($form->get('date_start')); ?>                  
                    </div>
                    <div class="form-group">
                    	<span>Time for Sale: </span>
                    	<span class="btn btn-info btn-sm" id="1-day">1 day</span>
                    	<span class="btn btn-info btn-sm" id="1-week">1 week</span>
                    	<span class="btn btn-info btn-sm" id="1-month">1 month</span>
                    </div>
                    <div>
                    	<label>Or choose specific day here</label>
                    </div>
                    <div class="form-group">
                        <?= $this->formLabel($form->get('date_end')); ?>
                        <?= $this->formElement($form->get('date_end')); ?>
                        <?= $this->formElementErrors($form->get('date_end')); ?>                  
                    </div>
                </div>
                <div class="box-footer">
                    <?= $this->formElement($form->get('submit')); ?>
                </div>
            <?= $this->form()->closeTag(); ?>   
        </div>
    </div>
</div>
