<md-layout md-vertical-align="center"
           md-gutter>
    <md-layout md-vertical-align="center"
               md-flex="66">
        <md-rating-bar v-model="rate_avg"
                       class="md-primary"
                       disabled>
        </md-rating-bar>
        <template v-if="product.rate_count == 0">Be the first to review this product</template>
        <template v-if="product.rate_count == 1">
            <b>{{ rate_avg }}</b>/5 on {{ product.rate_count }} review
        </template>
        <template v-if="product.rate_count > 1">
            <b>{{ rate_avg }}</b>/5 on {{ product.rate_count }} reviews
        </template>
    </md-layout>
    <md-layout md-align="end">
        <md-button class="md-primary md-raised"
                   @click="switchWriteReviewShowReview">
            <div v-show="!is_write_review">
                <md-icon>edit</md-icon>
                Write a review
            </div>
            <div v-show="is_write_review">
                View reviews
            </div>
        </md-button>
    </md-layout>
</md-layout>
<md-divider></md-divider>

<div class="list_review"
     v-show="!is_write_review">

    <md-list class="custom-list md-triple-line">
        <md-list-item v-for="(item, index) in product.review.items"
                      :key="index">
            <md-layout md-flex="20" md-column>
                <!--                <md-avatar md-align="center">-->
                <!--                    <img src="https://placeimg.com/40/40/people/1" :alt="item.user_name">-->
                <!--                </md-avatar>-->
                <b>{{ sort_user_name(item.user_name) }}</b>
            </md-layout>


            <div class="md-list-text-container">
                <md-rating-bar v-model="item.rate"
                               class="md-primary"
                               disabled>
                </md-rating-bar>
                <span>{{ item.content }}</span>
                <p>{{ item.date_created }} at {{ item.province }}</p>
            </div>

            <md-divider class="md-inset"></md-divider>
        </md-list-item>
    </md-list>
</div>

<div class="write_review"
     v-show="is_write_review && login">
    <h5>Please share your experience about this item</h5>
    <md-layout md-column>
        <md-layout md-vertical-align="center"
                   md-row>
            <b>Rate this product:</b>
            <md-rating-bar v-model="review.rate"
                           class="md-primary">
            </md-rating-bar>
            <div v-show="review.rate == 1">{{ review.rate }} star</div>
            <div v-show="review.rate > 1">{{ review.rate }} stars</div>
        </md-layout>
        <md-layout>
            <md-input-container>
                <md-icon>notes</md-icon>
                <label>Review</label>
                <md-textarea name="review content"
                             v-model="review.content"
                             maxlength="100">
                </md-textarea>
            </md-input-container>
        </md-layout>
    </md-layout>

    <md-layout md-align="center">
        <md-button class="md-primary md-raised"
                   @click="postReview">
            Submit review
        </md-button>
    </md-layout>
</div>

<div class="write_review"
     v-show="is_write_review && !login">
    <h5>Please <a :href="'/login?redirectUrl=/product/view/' + product.id">login</a> to write review</h5>
</div>
