<div class="category-bar js-category-bar">
    <div class="category-bar-content">
        <div class="category-bar-left">
            <div class="category-bar-menu">
                <button class="btn btn-cancel bt-infinitive" id="label-home" onclick="location.href = '/';">
                    Home
                </button>
                <ul class="menu-category-bar">
                    <li class="menu-item">
                        <button class="btn btn-cancel bt-infinitive" onclick="location.href = '#';">
                            Man
                        </button>
                    </li>
                    <li class="menu-item">
                        <button class="btn btn-cancel bt-infinitive" onclick="location.href = '#';">
                            Women
                        </button>
                    </li>
                    <li class="menu-item">
                        <button class="btn btn-cancel bt-infinitive" onclick="location.href = '#';">
                            Kid
                        </button>
                    </li>
                    <li class="menu-item">
                        <button class="btn btn-cancel bt-infinitive" onclick="location.href = '#';">
                            Sale
                        </button>
                    </li>
                </ul>
            </div>
        </div>
        <div class="category-bar-right">
            <ul>
                <?php if ($this->user == null) { ?>
                    <li class="menu-item signin-register">
                        <a href="/register">
                            <div class="menu-item label-category-bar">
                                Hello, Guest!
                            </div>
                        </a>
                    </li>
                <?php } else { ?>
                    <li class="has-dropdown menu-item signin-register">
                        <a href="/user/view">
                            <div class="menu-item label-category-bar">
                                Hello, <?php echo $this->user['name'] ?>
                            </div>
                        </a>
                    </li>
                <?php } ?>

                <li class="menu-item cart-info">
                    <a href="#">
                        <ul>
                            <li class="menu-item cart-icon">
                                <i class="fa fa-shopping-cart"></i>
                            </li>
                            <li class="menu-item" id="number_cart_item">
                                0
                            </li>
                            <li class="menu-item label-category-bar">
                                Cart
                            </li>
                        </ul>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>