<div class="footer">
    <!--<div class="email-signup text-center">-->
    <!--<div class="email-signup-content">-->
    <!--<h3>Get top trends and fresh Curie's picks in your inbox with Curated Stuff.</h3>-->
    <!--<form>-->
    <!--<input type="text" value="" id="mail-box" />-->
    <!--<input type="submit" value="Subscribe" class="btn btn-orange" id="subscribe-btn" />-->
    <!--</form>-->
    <!--</div>-->
    <!--</div>-->

    <div class="footer-inner">
        <div class="footer-content">
            <div class="container">
                <div class="col-sm-5">
                    <div class="clearfix">

                    </div>
                </div>
            </div>
            <div class="basic-info">
                <div class="container">
                    <div class="row">
                        <div class="pull-left">
                            <ul class="location-info">
                                <li>
                                    <i class="fa fa-globe fa-2x"></i>
                                </li>
                                <li>
                                    Viet Nam
                                </li>
                                <li>
                                    English(En)
                                </li>
                                <li>
                                    $(USD)
                                </li>
                            </ul>
                        </div>
                        <div class="pull-right">
                            <ul id="basic-info-right">

                                <li>
                                    © 2017 Infinitalk naite team.
                                </li>
                                <li>
                                    All Rights Reserved.
                                </li>
                                <li>
                                    <button type="button" class="btn btn-default">Infinitalk Co. Ltd.</button>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>