<div id="fh5co-footer" role="contentinfo">
    <div class="container">
<!--        <div class="row row-pb-md">-->
<!--            <div class="col-md-4 fh5co-widget">-->
<!--                <h3>Infini Shop.</h3>-->
<!--                <p>Trải nghiệm cảm giác mua hàng không giới hạn cùng InfiniShop.</p>-->
<!--            </div>-->
<!--        </div>-->

        <div class="row copyright">
            <div class="col-md-12 text-center">
                <p>
                    <small class="block">&copy; 2017 InfiniShop. All Rights Reserved.</small>
                    <small class="block">Designed by <a href="http://freehtml5.co/" target="_blank">InfiniShop</a>
                        Demo Images: <a href="http://zara.com/" target="_blank">Zara</a></small>
                </p>
                <p>
                <ul class="fh5co-social-icons">
                    <li><a href="#"><i class="icon-twitter"></i></a></li>
                    <li><a href="#"><i class="icon-facebook"></i></a></li>
                    <li><a href="#"><i class="icon-linkedin"></i></a></li>
                    <li><a href="#"><i class="icon-dribbble"></i></a></li>
                </ul>
                </p>
            </div>
        </div>
    </div>
</div>