<nav class="navbar navbar-default bootsnav">
    <div class="container-fluid curie_header">

        <!-- Start Header Navigation -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="/">
                INFINI SHOP
                <!--<img src="images/theme_logo.png" class="logo" alt="">-->
            </a>
        </div>
        <!-- End Header Navigation -->
        <div class="row">
            <div class="search-bar col-md-6">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="What are you shopping for?">
                    <span class="input-group-btn">
                    <button class="btn btn-secondary search-btn" type="button">Search</button>
                </span>
                </div>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-menu">
                <?php if ($user["id"] == null) { ?>
                    <ul id="hlink" class="nav navbar-nav navbar-right">

                        <li><a href="/">Home</a></li>
                        <li><a href="#">Track my order</a></li>
                        <li class="sign_li"><a href="/register" class="signin">Register</a></li>
                        <li><a href="/login">Signin</a></li>
                        <li class="cart_li">
                            <a href="/cart"><i class="fa fa-shopping-cart fa-2x"></i>
                                <span class="cart-logo"></span>
                            </a>
                        </li>
                    </ul>
                <?php } else { ?>
                    <?php include_once 'loggedInNavbar.phtml'?>
                <?php } ?>
            </div>
        </div>
    </div>
</nav>