<nav class="fh5co-nav" role="navigation">
    <div class="container" id="nav-contents">
        <div class="row">
            <div class="col-md-3 col-xs-2">
                <div id="fh5co-logo">
                    <div id="fh5co-logo-big"><a href="/">Infini</a></div>
                    <div id="fh5co-logo-small"><a href="/">Shop</a></div>
                </div>
            </div>
            <?php include_once "searchbar.phtml" ?>
        </div>

    </div>
</nav>