<div class="col-md-3 col-sm-6 col-xs-12">
    <a href="<?= $this->url('users', ['action' => 'list']); ?>">
        <div class="info-box">
            <span class="info-box-icon bg-red">
                <i class="glyphicon glyphicon-user">
                </i>
            </span>
            <div class="info-box-content">  
                <span class="info-box-text">Users</span>
                <span class="info-box-number">
                    <?= $number_of_users ?>    
                </span>
            </div>
        </div>
    </a>
</div>
<div class="col-md-3 col-sm-6 col-xs-12">
    <a href="<?= $this->url('products', ['action' => 'list']); ?>">
        <div class="info-box">
            <span class="info-box-icon bg-blue">
                <i class="glyphicon glyphicon-tag">
                </i>
            </span>
            <div class="info-box-content">
                <span class="info-box-text">Products</span>
                <span class="info-box-number">
                    <?= $number_of_products ?>
                </span>
            </div>
        </div>
    </a>
</div>

<div class="col-md-3 col-sm-6 col-xs-12">
    <a href="<?= $this->url('stores', ['action' => 'list']); ?>">
        <div class="info-box">
            <span class="info-box-icon bg-green">
                <i class="glyphicon glyphicon-home">
                </i>
            </span>
            <div class="info-box-content">
                <span class="info-box-text">Stores</span>
                <span class="info-box-number">
                    <?= $number_of_stores ?>
                </span>
            </div>
        </div>
    </a>
</div>

<div class="col-md-3 col-sm-6 col-xs-12">
    <a href="<?= $this->url('orders', ['action' => 'list']); ?>">
        <div class="info-box">
            <span class="info-box-icon bg-yellow">
                <i class="glyphicon glyphicon-phone-alt">
                </i>
            </span>
            <div class="info-box-content">
                <span class="info-box-text">Orders</span>
                <span class="info-box-number"></span>
            </div>
        </div>
    </a>
</div>
