<div class="row">
    <?php include_once '_data-info.phtml';?>
</div>

<div class="row">
    <div class="box">
        <div class="box-header">
            <h2 class="center">Sale Program</h2>
        </div>
        <div class="box-body">
            <?php include_once '_sale-program-info.phtml';?>
        </div>
    </div>
</div>
<div class="row">
    <div class="box">
        <div class="box-header">
            <h2 class="center">Order Quick Manager</h2>
        </div>
        <div class="box-body">
            <?php include_once '_order-info.phtml';?>
        </div>
    </div>
</div>
