<?= $this->form()->openTag($form); ?>

<div class="form-group">
    <?= $this->formLabel($form->get('name')); ?>
    <?= $this->formElement($form->get('name')); ?>
    <?= $this->formElementErrors($form->get('name')); ?>                  
</div>
<div class="form-group">
    <?= $this->formLabel($form->get('price')); ?>
    <?= $this->formElement($form->get('price')); ?>
    <?= $this->formElementErrors($form->get('price')); ?>                  
</div>
<div class="form-group">
    <?= $this->formLabel($form->get('image')); ?>
    <?= $this->formElement($form->get('image')); ?>
    <?= $this->formElementErrors($form->get('image')); ?>                  
</div>
<div class="form-group">
    <?= $this->formLabel($form->get('intro')); ?>
    <?= $this->formElement($form->get('intro')); ?>
    <?= $this->formElementErrors($form->get('intro')); ?>                  
</div>
<div class="form-group">
    <?= $this->formLabel($form->get('description')); ?>
    <?= $this->formElement($form->get('description')); ?>
    <?= $this->formElementErrors($form->get('description')); ?>                  
</div>
<?= $this->formElement($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>   
