<?php 
    $form->get('size')->setValue([1, 2, 3, 4, 5]);
?>
<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Add new Color to 
                    <a href="<?= $this->url('products', ['action' => 'view', 'id' => $product->getId()]) ?>">
                        <?php echo $product->getName() ?>
                    </a>
                </h3>
            </div>
            <div class="box-body">
                <?= $this->form()->openTag($form); ?>
                    <div class="col-md-10">
                        <?= $this->formLabel($form->get('color')); ?>
                        <?= $this->formElement($form->get('color')); ?>
                        <?= $this->formElementErrors($form->get('color')); ?>                  
                    </div>

                    <div class="col-md-10">
                        <br>
                        <?= $this->formLabel($form->get('size')); ?>
                        <?= $this->formElement($form->get('size')); ?>
                        <?= $this->formElementErrors($form->get('size')); ?>                  
                        <br>
                    </div>


                    <div class="col-md-10">
                        <label for="input-b3">Image Detail 1</label>
                            <input id="input-b3" name="image-details[]" type="file" class="file" 
                                data-show-upload="false"
                                data-show-caption="true"
                                data-theme="explorer"
                                data-allowed-file-extensions='["jpeg", "jpg", "png"]'>
                    </div>
                    <div class="col-md-10">
                        <label for="input-b3">Image Detail 2</label>
                            <input id="input-b3" name="image-details[]" type="file" class="file" 
                                data-show-upload="false"
                                data-show-caption="true"
                                data-theme="explorer"
                                data-allowed-file-extensions='["jpeg", "jpg", "png"]'>
                    </div>
                    <div class="col-md-10">
                        <label for="input-b3">Image Detail 3</label>
                            <input id="input-b3" name="image-details[]" type="file" class="file" 
                                data-show-upload="false"
                                data-show-caption="true"
                                data-theme="explorer"
                                data-allowed-file-extensions='["jpeg", "jpg", "png"]'>
                    </div>
                    <div class="col-md-10">
                        <label for="input-b3">Image Detail 4</label>
                            <input id="input-b3" name="image-details[]" type="file" class="file" 
                                data-show-upload="false"
                                data-show-caption="true"
                                data-theme="explorer"
                                data-allowed-file-extensions='["jpeg", "jpg", "png"]'>
                    </div>
                    <br>
                    <div class="col-md-10">
                        <br>
                        <?= $this->formElement($form->get('submit')); ?>
                    </div>


                <?= $this->form()->closeTag(); ?>   
            </div>    
        </div>
    </div>
</div>
