
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Add new Product</h3>
            </div>
            <div class="box-body">
                <?= $this->form()->openTag($form); ?>
                <!-- left row -->
                <div class="col-md-5 col-xs-12 col-sm-5 ">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('name')); ?>
                        <?= $this->formElement($form->get('name')); ?>
                        <?= $this->formElementErrors($form->get('name')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('category_id')); ?>
                        <?= $this->formElement($form->get('category_id')); ?>
                        <?= $this->formElementErrors($form->get('category_id')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('price')); ?>
                        <?= $this->formElement($form->get('price')); ?>
                        <?= $this->formElementErrors($form->get('price')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('intro')); ?>
                        <?= $this->formElement($form->get('intro')); ?>
                        <?= $this->formElementErrors($form->get('intro')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('description')); ?>
                        <?= $this->formElement($form->get('description')); ?>
                        <?= $this->formElementErrors($form->get('description')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('status')); ?>
                        <?= $this->formElement($form->get('status')); ?>
                        <?= $this->formElementErrors($form->get('status')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('keywords')); ?>
                        <?= $this->formElement($form->get('keywords')); ?>
                        <?= $this->formElementErrors($form->get('keywords')); ?>                  
                        <p class="help-block">Separate tags with comma.</p>
                    </div>

                    <div class="form-group">
                        <?= $this->formElement($form->get('submit')); ?>
                    </div>
                </div>
                <!-- end left row -->
                <div class="col-md-7 col-xs-12 col-sm-7 ">
                    <div class="row">
                        <div class="col-md-8">
                            <label for="input-b3">Select File</label>
                            <input id="input-b3" name="image" type="file" class="file" 
                                data-show-upload="false"
                                data-show-caption="true"
                                data-allowed-file-extensions='["jpeg", "jpg"]'>
                        </div>
                    </div>
                    <br>
                    <br>
                    <img src="<?php echo $this->basePath($product->getImage()) ?>" class="book-image width-custom">
                </div>


                <?= $this->form()->closeTag(); ?>   
            </div>    
        </div>
    </div>
</div>

