<?php
    $form->prepare();
?>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Edit Product</h3>
            </div>
            <div class="box-body">
                <?= $this->form()->openTag($form); ?>
                <!-- left row -->
                <div class="col-md-4 col-xs-12 col-sm-4 ">
                    <div class="form-group">
                        <?= $this->formLabel($form->get('name')); ?>
                        <?= $this->formElement($form->get('name')); ?>
                        <?= $this->formElementErrors($form->get('name')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('category_id')); ?>
                        <?= $this->formElement($form->get('category_id')); ?>
                        <?= $this->formElementErrors($form->get('category_id')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('price')); ?>
                        <?= $this->formElement($form->get('price')); ?>
                        <?= $this->formElementErrors($form->get('price')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('status')); ?>
                        <?= $this->formElement($form->get('status')); ?>
                        <?= $this->formElementErrors($form->get('status')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('intro')); ?>
                        <?= $this->formElement($form->get('intro')); ?>
                        <?= $this->formElementErrors($form->get('intro')); ?>                  
                    </div>


                    <div class="form-group">
                        <?= $this->formLabel($form->get('description')); ?>
                        <?= $this->formElement($form->get('description')); ?>
                        <?= $this->formElementErrors($form->get('description')); ?>                  
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($form->get('keywords')); ?>
                        <?= $this->formElement($form->get('keywords')); ?>
                        <?= $this->formElementErrors($form->get('keywords')); ?>                  
                        <p class="help-block">Separate tags with comma.</p>
                    </div>


                </div>
                <!-- right row -->
                <div class="col-md-8 col-xs-12 col-sm-8 ">
                    
                
                
                    <div class="well" id="field-color">
                        <div class="row">
                            <div class="col-md-6">
                            <?= $this->formCollection($form->get('image'));?>

                            </div>
                            <div class="col-md-1"></div>
                            <div class="col-md-5">
                            <br><br><br><br><br><br><br><br><br><br><br><br>
                                <?php foreach ($images as $image) :?>
                                    <img src="<?php echo $this->basePath($image['image']) ?>" class="width-250">
                                    <br><br>
                                    <div>
                                    <?php foreach ($image['detail'] as $detail) { ?>
                                        <img src="<?php echo $this->basePath($detail) ?>" class="width-50 ">
                                    <?php } ?>
                                    </div>
                                    
                                    <br><br><br>
                                <?php endforeach ?>
                                
                            </div>

                        </div>
                    </div>
                    
                    
                    <div class="form-group">
                        <?= $this->formElement($form->get('submit')); ?>
                    </div>
                </div>
                <!-- end right row -->

                <?= $this->form()->closeTag(); ?>   
            </div>
        </div>
    </div>
</div>
