<h1>Products</h1>

<div class="box-body">
    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">

        <thead>
            <tr>
                <th>ID</th>
                <th>Image</th>
                <th>Name</th>
                <th>Option</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($products as $product): ?>
            <tr>
                <td><?php echo ++$i ?></td>
                <td>
                    <img src="<?php echo $this->basePath($product->getImage()) ?>" class="image_product">
                </td>
                <td><?php echo $product->getName(); ?></td>
                <td>
                    <a href="">
                        <i class="glyphicon glyphicon-log-in"></i>
                    </a>
                    <a href="<?= $this->url('products', ['action' => 'edit', 'id' => $product->getId()]) ?>">
                        <i class="glyphicon glyphicon-edit"></i>
                    </a>
                    <a href="<?= $this->url('products', ['action' => 'delete', 'id' => $product->getId()]) ?>">
                        <i class="glyphicon glyphicon-trash"></i>    
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>    
        </tbody>
    </table>
</div>
