<div class="box-body">
    <h2 class="margin-bottom-20">
        <?php echo $product->getName() ?></h2>

    <div class="row">
        <div class="col-md-5">
            <img src="<?php echo $this->basePath($product->getImage()) ?>" class="book-image width-custom">
        </div>

        <div class="col-md-6">
            <table class="table table-striped table-bordered">
                <tr>
                    <th>Name:</th>
                    <td>
                    <?= $this->escapeHtml($product->getName()) ?></td>
                </tr>
                <tr>
                    <th>Category:</th>
                    <td>
                        <?php if ($product->getCategory() != null){ ?>
                        <a href="<?= $this->url('categories',
                            ['action' => 'view', 'id' => $product->getCategory()->getId()]) ?>">
                        <?php echo $product->getCategory()->getName(); ?>
                        <?php } ?>
                    </a>
                    </td>
                </tr>
                
                <tr>
                    <th>Price:</th>
                    <td>
                    <?= $this->escapeHtml($product->getPrice()) ?></td>
                </tr>
                
                <tr>
                    <th>Size:</th>
                    <td>
                    <?php 
                        foreach ($sizes as $size){
                            echo $size.'  ';
                        }
                     ?>
                        
                    </td>
                </tr>

                <tr>
                    <th>Intro:</th>
                    <td>
                    <?= $this->escapeHtml($product->getIntro()) ?></td>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td>
                    <?= $this->escapeHtml($product->getDescription()) ?></td>
                </tr>
                <tr>
                    <th>Date Created:</th>
                    <td>
                    <?= $this->escapeHtml($product->getDateCreated()) ?></td>
                </tr>
            </table>
            <button class="btn btn-primary btn-sm"><a href="<?= $this->url('products', ['action' => 'addcolor', 'id' => $product->getId()]) ?>">
                Add new color
            </a></button>
        </div>

    </div>
</div>
