<div class="box-body">
    <h2 class="margin-bottom-20">
        <?php echo 'Infomation of product '.$product->getName().' : '?></h2>

    <div class="row">
        <div class="col-md-6">
            <table class="table table-striped table-bordered">
                <tr>
                    <th>Name:</th>
                    <td>
                    <?= $this->escapeHtml($product->getName()) ?></td>
                </tr>
                <tr>
                    <th>Category:</th>
                    <td>
                        <?php if ($product->getCategory() != null){ ?>
                        <a href="<?= $this->url('categories',
                            ['action' => 'view', 'id' => $product->getCategory()->getId()]) ?>">
                        <?php echo $product->getCategory()->getName(); ?>
                        <?php } ?>
                    </a>
                    </td>
                </tr>
                
                <tr>
                    <th>Price:</th>
                    <td>
                    <?= $this->escapeHtml($product->getPrice()) ?></td>
                </tr>
                
                <tr>
                    <th>Size:</th>
                    <td>
                    <?php 
                        foreach ($sizes as $size){
                            echo $size.'  ';
                        }
                     ?>
                        
                    </td>
                </tr>

                <tr>
                    <th>Intro:</th>
                    <td>
                    <?= $this->escapeHtml($product->getIntro()) ?></td>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td>
                    <?= $this->escapeHtml($product->getDescription()) ?></td>
                </tr>
                <tr>
                    <th>Date Created:</th>
                    <td>
                    <?= $this->escapeHtml($product->getDateCreated()) ?></td>
                </tr>
             </table>
        </div>

        <div class="col-md-1"></div>

        <div class="col-md-5">
            <h2> Image : </h2>
            <?php foreach ($images as $image) :?>
                
                
                <img src="<?php echo $this->basePath($image['image']) ?>" class="width-custom">
                <br><br>
                <div>
                <?php foreach ($image['detail'] as $detail) { ?>
                    <img src="<?php echo $this->basePath($detail) ?>" class="width-50 inline">
                <?php } ?>
                </div>
                <h4>Size of image : 
                    <?php 
                        foreach ($image['size'] as $size) {
                            echo $size.'  ';
                        }
                     ?>
                </h4>
                <br><br>
            <?php endforeach ?>
        </div>
    </div>
</div>
