<div class="tracking-outer">
    <div class="container">
        <nav class="nav navbar-default">
            <div class="navbar-brand">
                <a href="/">InfiniShop - Track your product</a>
            </div>
        </nav>
        <div class="track-product order-data">
            <div class="row">
                <div class="col-lg-3 col-sm-3 col-xs-12">
                    <div class="track-product-img">
                        <img src="/ecommerce/html5/darwin/demo/img/bangolufsen.jpg" alt="img" class="image-responsive" width="100%" />
                    </div>
                </div>
                <div class="col-lg-9 col-sm-9 col-xs-12">
                    <div class="track-product-description">
                        <div class="p-data clearfix">
										<span class="pull-left">
											June 16TH - 7:22PM<br/>
											Bang and Olufsen B & O Play
										</span>
                            <span class="pull-right">
											<b>499$</b>
										</span>
                        </div>
                        <p style="margin-top:20px;font-weight:900;" class="trach_h">Order details</p>
                        <div class="row">
                            <div class="col-lg-4 col-sm-4">
                                <b>Product:</b><br/>
                                Bang and Olufsen B & O Play
                            </div>
                            <div class="col-lg-2 col-sm-2">
                                <b>Quantity:</b><br/>
                                1 x bagpack	Free
                            </div>
                            <div class="col-lg-2 col-sm-2">
                                <b>Shiping:</b><br/>
                                Free
                            </div>
                            <div class="col-lg-2 col-sm-2">
                                <b>Subtotal:</b><br/>
                                100 $
                            </div>
                            <div class="col-lg-2 col-sm-2">
                                <b>Total:</b><br/>
                                399 $
                            </div>
                        </div>
                        <p style="margin-top:20px;font-weight:900;" class="trach_h">Customer Details</p>
                        <div class="row">

                            <div class="col-lg-4 col-sm-4">
                                <b>Mail/Phone:</b><br/>
                                darwin@premium-themes.org<br/>
                                +1 (150) 123-41-425

                            </div>
                            <div class="col-lg-4 col-sm-4">
                                <b>Billing address:</b><br/>
                                Chestnut St. 2125<br/>
                                San Francisco, CA 94123
                            </div>
                            <div class="col-lg-4 col-sm-4">
                                <b>Shipping address:</b><br/>
                                Chestnut St. 2125<br/>
                                San Francisco, CA 94123
                            </div>

                        </div>
                        <div class="inner-table">
                            <p class="trach_h">
                                Track your product here
                            </p>
                            <ul class="progress-indicator">
                                <li class="warning">
                                    <span class="bubble"></span>
                                    Order Received
                                </li>
                                <li class="danger">
                                    <span class="bubble"></span>Order Packed
                                </li>

                                <li class="info">
                                    <span class="bubble"></span>In Warehouse
                                </li>
                                <li class="completed">
                                    <span class="bubble"></span>Package Dispatched
                                </li>
                                <li>
                                    <span class="bubble"></span><span class="fa fa-calender">Order Delivered
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>