<div class="order-outer" id="order">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="track_product clearfix">
                        <a class="order-num btn btn-medium btn-blue col-xs-12 col-lg-3 col-sm-4 col-md-4"
                           target="_blank" href="#">
                            OD206437975731573000
                        </a>
                        <a href="/order/track"
                           class="btn btn-default track pull-right col-xs-12 col-lg-2 col-sm-2 col-md-2">
                            <i class="fa fa-map-marker map-tack-icon"></i>
                            &nbsp; Track
                        </a>
                    </div>
                </div>
                <div class="panel-body order-body">
                    <div id="order-panel">
                        <div class="order-item">
                            <div class="row">
                                <div class="col-lg-2 col-md-2 col-sm-2">
                                    <div class="product_image text-center">
                                        <img src="/ecommerce/html5/darwin/demo/img/levibe.jpg" />
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3">
                                    <div class="product_descp">
                                        <a href="#">Lenovo Vibe K5 Plus </a>
                                        <p class="small">
                                            Color: Silver &nbsp; Qty: 1 &nbsp;
                                            <br>Seller: Hubbard Retail </p>
                                        </p>
                                    </div>
                                </div>
                                <div class="col-lg-2 col-md-2 col-sm-2">
                                    <div class="product_rate">
                                        <p class="small">
                                            $99 <br />
                                            <span class="offers">OFFERS:</span> 2
                                        </p>
                                    </div>
                                </div>
                                <div class="col-lg-5 col-md-5 col-sm-5">
                                    <div class="product_status">
                                        <p>Returned</p>
                                        <p class="small">Refund successful!?<br /> $99 has been remitted through
                                            original
                                            payment
                                            mode </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="line order-total">
                            <div class="line clearfix">
                                <div class="pull-right">
                                    <span class="smallText">Order Total:</span>
                                    <strong>$99</strong>
                                </div>
                                <div class="order_data">
                                    <span>Date:</span> Sun, 3rd Jul'16
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <div class="clearfix action_group">
                        <button type="button" class="btn btn-danger pull-right">Return</button>
                        <button type="button" class="btn btn-info pull-right">Download</button>
                        <button type="button" class="btn btn-default pull-right">Review</button>
                    </div>
                </div>
            </div>
            <div class="no-data">
                <span class="no-data-icon"><i class="fa fa-sticky-note-o" aria-hidden="true"></i></span>
                <p>You haven’t made any purchases yet.</p>
            </div>
        </div>
    </div>
</div>
